### ISSUE TITLE
using dub and ddoc triggers a warning

### ISSUE THREAD

**Issue by gedaiu** [adamdruppe/arsd#103]
terminal.d(2555,17): Warning: Ddoc: Stray '('. This may cause incorrect Ddoc output. Use $(LPAREN) instead for unpaired left parentheses.

**Comment by adamdruppe** [comment]
fixed, a typo in my text. If you are on master you'll already see it and i also tagged 1.2.1 for dub.

Though note that I don't actually use ddoc, I have a custom syntax, so the ddoc output might look a little bit weird anyway (while probably still being legible). Best source for my docs though is http://dpldocs.info/arsd.terminal

**Comment by gedaiu** [comment]
thanks!
