### ISSUE TITLE
utf8 support on windows?

### ISSUE THREAD

**Issue by gedaiu** [adamdruppe/arsd#107]
I know that I might ask for too much but it seems that it's impossible to have utf8 chars on windows command prompt... or there is something that I am missing?

**Comment by adamdruppe** [comment]
On Sat, Jul 08, 2017 at 12:39:44PM -0700, Szabo Bogdan wrote:
> I know that I might ask for too much but it seems that it's impossible to have utf8 chars on windows command prompt... or there is something that I am missing? 

On Windows, you need to configure the command prompt to use the utf-8
code page (`chcp 65001` from the command line) and set it to use a font
with the charset in the properties sheet.

Win10 might have better support out of the box though, perhaps I can
do some of it in the program, but changing the font at least needs to
be done by the user.

**Comment by adamdruppe** [comment]
I just pushed a commit to automatically do this, now that Windows 10 out of the box comes with excellent utf-8 support in the built in font. And on other systems, it will still mostly work anyway. so finally time to close this :)
