### ISSUE TITLE
statement not reachable in jsvar/script

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#111]
For following code dmd output "statement not reachable error":

```
import arsd.script, arsd.jsvar;
import std.ascii: newline;
var globals = var.emptyObject;
		
string scriptOutput;
		
globals.writeln = (string s) {
	scriptOutput ~= s~newline;
};
```

source\arsd\jsvar.d(712,4): Warning: statement is not reachable
```
			case Type.Function:
				assert(0); // FIXME
			break;
```

source\arsd\script.d(2525,5): Warning: statement is not reachable
```
				case "assert":
					tokens.popFront();

					return parseFunctionCall(tokens, new AssertKeyword(token));

				break;
```

**Comment by andre2007** [comment]
I just found out, issue is related to the usage of dub, which sets the compiler setting "stop on warnings"...
Before I was using dmd directly

**Comment by adamdruppe** [comment]
Yeah, dub uses warnings as error but I thought I fixed that anyway, double
check what version you have.

The power is out at my house so I'm only half-online right now, but the
solution in the source is to just comment the breaks after the assert. I
always write case/break just like {}, even if i assert/return right there
too, but dmd with warnings enabled complains about it.

**Comment by andre2007** [comment]
I have recent version of the source files:
https://github.com/adamdruppe/arsd/blob/master/jsvar.d#L712
https://github.com/adamdruppe/arsd/blob/master/script.d#L2525

**Comment by adamdruppe** [comment]
I finally got back to this and fixed it. Sorry for the year wait, I TOTALLY forgot about this once the power got back on last year.
