### ISSUE TITLE
jsvar empty object not working?

### ISSUE THREAD

**Issue by Ajusa** [adamdruppe/arsd#112]
```
script.d(3): Error: no identifier for declarator globals.x
script.d(3): Error: declaration expected, not '='
Failed: ["dmd", "-v", "-o-", "main.d", "-I."]

```
This is the error I get for trying to play with the example from the jsvar.d file.
```
var globals = var.emptyObject;
globals.x = 25;
```

**Comment by adamdruppe** [comment]
Did you `import arsd.jsvar;`?

**Comment by Ajusa** [comment]
Yeah. It's fine with me doing "var a = 5", so I believe that the import is working

**Comment by Ajusa** [comment]
Right now, I am trying to embed the arsd.script stuff in a project. I will try it without the project just to see if it works on my machine (win 10 64bit)

**Comment by adamdruppe** [comment]
the no property thing could also potentially be caused by a compile
error. Maybe the warnings thing again?

I'll be able to look at this in more detail later today, I just got home
from a trip though so catching up on a bunch of things.

**Comment by Ajusa** [comment]
Okay, that's fine. 
I am doing just "rdmd main.d", not using sub for anything btw. I believe you are referring to the other issue that someone had a few days ago.

**Comment by Ajusa** [comment]
I figured it out. This might be completely my fault, since I don't code in D very often. I thought that I should be able to define the var stuff within a class variables, but instead it has to actually be defined within the constructor. Once I did that, everything worked. Thank you for trying to help me! Sorry about the "non-issue".

**Comment by adamdruppe** [comment]
oooh, I should have realized that from the error message!

Well, I hope it is being useful to you.
