### ISSUE TITLE
Interface for cgi.d

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#114]
While it is easy to build an embedded http server using cgi library it is quite hard to find out how to develop an own main function which starts the http server.

Use cases:
- I want to execute some logic before the http server gets started
- I want to listen on port provided in environment variable PORT if set otherwise on port 8080

It is possible to figure out by reading the source code, but for a beginner it is quite hard.

A "deluxe" solution would be to provide an interface like this:

```
void main()
{
  with(new HTTPServer)
  {
    onRequest = &handleRequest;
  
    import std.conv, std.process;
    port = environment.get("PORT", "8080").to!ushort;
    active = true;
  }
}

void handleRequest(Cgi cgi) {...}
```

As easy solution you maybe could enhance the DDOC to show how to use an own main function which also sets the http server port

**Comment by adamdruppe** [comment]
On Tue, Oct 10, 2017 at 08:13:01PM +0000, andre2007 wrote:
> While it is easy to build an embedded http server using cgi library it is quite hard to find out how to develop an own main function which starts the http server.

It is actually completely unsupported at this time... I never settled
on how I wanted to do it.

I guess best right now wold be

        mixin CustomCgiMainImpl!(Cgi, your_main_fun, defaultMaxContentLength) customCgiMainImpl_;

        void main(string[] args) {
		// put your before stuff here
		// you can also add args ~= ["--port", "whatever"]
		// to change that
                customCgiMainImpl_.cgiMainImpl(args);
        }

But it isn't documented cuz I might decide to change that....

I guess I will see about defining a public api soon.

**Comment by adamdruppe** [comment]
I just fixed this one this week! The `cgiMainImpl` is now public, though not documented. You still have to pass it its command line arguments in a few ways, so gonna leave it open, but it is a lot easier than it used to be.

**Comment by adamdruppe** [comment]
I'm gonna close this now because there's now a supported and documented http://arsd-official.dpldocs.info/arsd.cgi.RequestServer.html RequestServer thing you can do more structured!
