### ISSUE TITLE
Incorect icon loading on X64.

### ISSUE THREAD

**Issue by zero-vector** [adamdruppe/arsd#116]
Icon data are still uints but stored in ulong.

https://github.com/adamdruppe/arsd/blob/b4cf5d0c469538a8415f89bc8a920dd599e3dea6/simpledisplay.d#L12465

something like this:
```
auto imageData = new ubyte[](4 * width * height);
for (int idx = 0, idx2 = 0; idx < bytes.length; idx += arch_ulong.sizeof, idx2 += 4) {
    r = bytes[idx + 2];
    g = bytes[idx + 1];
    b = bytes[idx + 0];
    a = bytes[idx + 3];

    imageData[idx2 + 0] = r;
    imageData[idx2 + 1] = g;
    imageData[idx2 + 2] = b;
    imageData[idx2 + 3] = a;
}
icon = new TrueColorImage(width, height, imageData);
```

**Comment by adamdruppe** [comment]
ok i took your ideas and checked with the man page

latest commit seems to fix it well for me.

I hate that a /32 is 64 bits long sometimes. C is evil.

**Comment by zero-vector** [comment]
This seems to work, thanks.
