### ISSUE TITLE
http2 is not working without openssl/crypto lib

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#118]
I tried to use http2 without setting version to use_openssl. Unfortunately this line will always force openssl

https://github.com/adamdruppe/arsd/blob/master/http2.d#L1240
```version=use_openssl;```

If I comment this line out, there is a syntax error because in this line
https://github.com/adamdruppe/arsd/blob/master/http2.d#L457
SslClientSocket is used, which is not available now anymore.

```
Socket socket;
	if(ssl)
		socket = new SslClientSocket(AddressFamily.INET, SocketType.STREAM);
	else
		socket = new Socket(AddressFamily.INET, SocketType.STREAM);
```

**Comment by adamdruppe** [comment]
On Mon, Oct 16, 2017 at 11:55:51AM -0700, andre2007 wrote:
> I tried to use http2 without setting version to use_openssl. Unfortunately this line will always force openssl

I pushed a new commit try -version=without_openssl now

**Comment by andre2007** [comment]
Thanks a lot :) Now it is working.
