### ISSUE TITLE
getline/getch in unittests of terminal.d causes issues

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#119]
It is only a small issue but I thought I mention it. In my application I am using terminal.d and I have also some unittests. While running the unittests, the unittest run stops at the unittests of terminal.d as a user input is expected:

https://github.com/adamdruppe/arsd/blob/master/terminal.d#L78
https://github.com/adamdruppe/arsd/blob/master/terminal.d#L113

I solved the issue by deactivating this lines.

**Comment by adamdruppe** [comment]
On Wed, Oct 18, 2017 at 12:00:49PM -0700, andre2007 wrote:
> I solved the issue by deactivating this lines.

huh, I am a bit surprised it runs them at all since they are wrapped
in nested functions.

Are you using plain dmd -unittest or some other facility?

**Comment by andre2007** [comment]
Sorry, it was an error on my side. I commented out the "void main() {" lines in the unittests of terminal.d because I was investigating an error "only one main method allowed". I thought it was caused by these lines in the unittest. Actually it was an dub bug (https://github.com/dlang/dub/issues/1270).
I forget to activating these lines again...which now caused the stopping unittests.
