### ISSUE TITLE
Png Issue

### ISSUE THREAD

**Issue by taylorh140** [adamdruppe/arsd#123]
I found a png that does not seem to load properly.
![font](https://user-images.githubusercontent.com/10996543/33634962-b412255c-d9db-11e7-9137-655aae2770e7.png)

When viewing in the simply display it looks like this.

![2017-12-05_16-46-35](https://user-images.githubusercontent.com/10996543/33635004-e31bb02a-d9db-11e7-83f2-6d008de0136f.png)

I am using (Win 7 32 bit).

If you need any more information let me know.

**Comment by adamdruppe** [comment]
On Tue, Dec 05, 2017 at 10:48:04PM +0000, Taylor Hillegeist wrote:
> When viewing in the simply display it looks like this.

simpledisplay doesn't support alpha transparency.

Ensure the file doesn't use any.

**Comment by taylorh140** [comment]
Good to know! Thanks!

**Comment by adamdruppe** [comment]
So the png loads correctly, but since the alpha channel is discarded
before displaying, transparent pixels get their color displayed which
happens to be green in this image.

**Comment by adamdruppe** [comment]
btw i have considered implementing 1-bit transparency, but i haven't
gotten around to it yet

also maybe possible to do it cross platform with an X extension for 8 bit
but i haven't even started that yet.

**Comment by taylorh140** [comment]
Cool. That would make simpledisplay much better for sprites/games/such.

**Comment by adamdruppe** [comment]
for games, you might just want to use the openGL functions, which do support
full blending already btw.

http://dpldocs.info/experimental-docs/arsd.simpledisplay.OpenGlOptions.html

well that example is a bit thin. but you just draw in there using regular
opengl functions (it defaults to the old style glBegin/glEnd, though you
can opt into higher versions with http://dpldocs.info/experimental-docs/arsd.simpledisplay.setOpenGLContextVersion.html )

**Comment by taylorh140** [comment]
`import arsd.simpledisplay;
import arsd.png;


void main() {

	auto window = new SimpleWindow(600, 400, "Window",OpenGlOptions.yes);
	// Set up the matrix
	window.setAsCurrentOpenGlContext(); // make this window active

	auto FontSrc = (readPng("Font.png"));

	// This is called on each frame, we will draw our scene
	window.redrawOpenGlScene = delegate() {
		auto painter = window.draw();
		painter.clear();
		painter.drawImage(Point(0,0),Image.fromMemoryImage(FontSrc));
	};

	window.eventLoop(0,
				(KeyEvent ev) {
					if (ev.pressed) window.close();
				} );


}`

Can i ask if I'm close?

**Comment by adamdruppe** [comment]
On Tue, Dec 05, 2017 at 11:31:58PM +0000, Taylor Hillegeist wrote:
> 	// This is called on each frame, we will draw our scene
> 	window.redrawOpenGlScene = delegate() {
> 		auto painter = window.draw();
> 		painter.clear();
> 		painter.drawImage(Point(0,0),Image.fromMemoryImage(FontSrc));
> 	};
> 
> Can i ask if I'm close?

Nope.... redrawOpenGlScene only works with the open GL functions, not the
painter anymore. It is an entirely different kind of programming. Images
need to be loaded into textures and drawn as rectangles...

the gamehelpers.d has two useful functions:
https://github.com/adamdruppe/arsd/blob/master/gamehelpers.d


`create2dWindow` will make a SimpleWindow of the correct size with a 2d
matrix, and `OpenGlTexture` gives an image loader.

So you can do something like:

auto window = create2dWindow("title", 400, 400); // size
auto image = new OpenGlTexture(readPng("file.png"));

window.redrawOpenGlScene = () {
	image.draw(Point(0, 0);
};

window.eventLoop ......


That should get started. You might want to copy/paste that OpenGlTexture
class and the create2dWindow function to your code to avoid the dependencies
gamehelpers has.
