### ISSUE TITLE
sqlite.d: automatic binding doesn't work for ints > 32-bit

### ISSUE THREAD

**Issue by quickfur** [adamdruppe/arsd#125]
Test code:
````
import arsd.sqlite;
void main() {
        auto sql = new Sqlite("test.db");
        sql.query("CREATE TABLE tab (oid INTEGER PRIMARY KEY, x INTEGER, y INTEGER)");
        sql.query("INSERT INTO tab (x,y) VALUES(?,?)", 123, 1_000_000_000_000L);
}
````

Here's the result of inspecting the resulting database file with the command-line client:
````
$ sqlite3 test.db
SQLite version 3.21.0 2017-10-24 18:55:49
Enter ".help" for usage hints.
sqlite> select * from tab;
1|123|
sqlite> 
````

Expected result: the 3rd column should have the value `1000000000000` stored.

So far, in my code, I've been working around this by forcing all 64-bit values into strings; that works around the mysterious disappearing values, but it also has the drawback that SQLite will treat it as a string value, so comparisons / sorting in `WHERE` clauses can sometimes misbehave in strange ways, probably due to it using string comparisons instead of 64-bit int comparisons.

A cursory glance at the code seems to show that only 32-bit ints are bound; I'm not sure what happens with 64-bit ints. Gotta run now, maybe I'll take a shot at fixing this myself tomorrow.

**Comment by adamdruppe** [comment]
On Wed, Dec 13, 2017 at 02:33:29AM +0000, H. S. Teoh wrote:
> A cursory glance at the code seems to show that only 32-bit ints are bound; I'm not sure what happens with 64-bit ints. Gotta run now, maybe I'll take a shot at fixing this myself tomorrow.

yeah, I expect they are just discarded. It uses a crappy runtime
variadic since this code predates templates in interfaces.

Should be able to do MUCH better in less code rewriting it now.

**Comment by quickfur** [comment]
Here's my go at fixing this: https://github.com/adamdruppe/arsd/pull/126
