### ISSUE TITLE
Terminal background color issue in Windows Powershell

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#128]
In recent windows versions Microsoft unfortunately is deprecating the Command Prompt in favour of the Windows Powershell.

While this coding is working as expected in the command prompt, there is some issue in the Powershell.

```
import arsd.terminal;

void main()
{
                Terminal terminalInstance = Terminal(ConsoleOutputType.linear);
                terminalInstance.color(Color.green | Bright, Color.DEFAULT);
                terminalInstance.writeln("Hello World!");
                terminalInstance.color(Color.DEFAULT, Color.DEFAULT);
}
```
Windows Powershell has a blue background. Only the text "Hello World!" has black background.
It seems Color.DEFAULT detects the Command Prompt color and not the Powershell color.

I validated dmd compiler and the colored output is working fine in Powershell.

**Comment by adamdruppe** [comment]
On Mon, Jan 08, 2018 at 11:50:54AM -0800, andre2007 wrote:
> It seems Color.DEFAULT detects the Command Prompt color and not the Powershell color.

It doesn't actually detect at all - it just assumes black on Windows.

I'll have to look up a way to correctly confirm that.... I'll get back
to you in a little bit.

**Comment by andre2007** [comment]
Maybe as side information, recent Windows 10 also support now the posix colour codes. More information on this topic you can find at the end of this pr https://github.com/dlang/dub/pull/1490.

This should also solve the background issue on Windows.

**Comment by adamdruppe** [comment]
Yeah, I will have to change the code a little. I will look at it when I am back home (I'm on vacation right now)

**Comment by andre2007** [comment]
Thanks a lot and enjoy your vacation :)

**Comment by adamdruppe** [comment]
So I didn't add the ansi support to Windows, but I did have an idea to detect default attributes: just store the current state in the constructor and assume that is the default. It seems to work really well for me in a lot of combinations (including my own preferred black on white scheme). Wanna update your terminal.d and see if it works for you too.

**Comment by andre2007** [comment]
It works like a charm, thank you so much.
