### ISSUE TITLE
Mysql Database Error

### ISSUE THREAD

**Issue by sathanu** [adamdruppe/arsd#129]
I got the below error when run the program by dub run.
Please help to me fix it. 
What are all the libraries required and how to install them ?
And Provide one Sample application using mysql and sqlite.

Performing "debug" build using dmd for x86.
consolelambda ~master: building configuration "application"...
Linking...
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
libmysql.lib
 Warning 2: File Not Found libmysql.lib
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_free_result@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_fetch_fields@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_num_fields@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_num_rows@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_fetch_row@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_fetch_lengths@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_real_connect@32
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_init@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_error@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_close@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_insert_id@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_real_escape_string@16
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_affected_rows@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_store_result@4
.dub\build\application-debug-windows-x86-dmd_2077-42B94A4D8CC820E580CFF74D6850F2F1\consolelambda.obj(consolelambda)
 Error 42: Symbol Undefined _mysql_query@8
Error: linker exited with status 15
dmd failed with exit code 15.

**Comment by adamdruppe** [comment]
I just wrote an email but not sure if github accepted it...

**Comment by adamdruppe** [comment]
blargh the attachments blocked. So you need the mysql C library. They offer an official download here: https://dev.mysql.com/downloads/connector/c/ looks like you want Windows 32 bit.

The DLL there can be installed, or copied along with your exe. The lib in there though will only work with `-m32mscoff` builds (requires Visual Studio in addition to the D compiler). For default dmd builds you will want the lib file adapted for optlink. I made one here: http://arsdnet.net/libmysql.lib just adding that lib to your source directory should let the program build.

**Comment by adamdruppe** [comment]
Did you have any luck with it?
