### ISSUE TITLE
mysql build fails an 64bit machine

### ISSUE THREAD

**Issue by Ssamm45** [adamdruppe/arsd#132]
When I build something with mysql.d on my 64bit linux machine I get:

`source/mysql.d(46,22): Error: cannot implicitly convert expression this.length() of type ulong to int`

I assume this is because on a 32bit machine size_t is defined as uint but on a 64bit machine it is ulong.
It will compile for me if I change line 46 from

`itemsTotal = length()` 

to 

`itemsTotal = length().to!int`

I am not sure if that is the best solution to the problem or the only place that it needs te be fixed. Another solution could be to change `itemsTotal` on line 39 from an `int` to a `size_t`

**Comment by adamdruppe** [comment]
Oh yeah, I changed the interface recently but didn't retest on 64 bit. Easy fix, I usually just `cast(int)` it.

Push fixed now, try the new version and you should be all good.

**Comment by Ssamm45** [comment]
It's working properly now.
