### ISSUE TITLE
Terminal hangs on windows pipe

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#138]
I compiled following application and run on windows 10 command prompt using command
```app > test.log```
The application will run  forever. The purpose is to write the result of the application into a text file.

```
import arsd.terminal;

void main(string[] args)
{
    Terminal terminalInstance = Terminal(ConsoleOutputType.linear);
    terminalInstance.writeln("Hello World!");
}
```

**Comment by andre2007** [comment]
Problem occurs only on windows. On linux pipes are working fine.

**Comment by adamdruppe** [comment]
Sorry I forgot to answer this yesterday. But you aren't supposed to use `Terminal` on pipes, it should probably just check that and throw an exception if it isn't one. Even on linux, there's several operations that do not work on pipes (just writing happens to be one of the few that does...)

**Comment by andre2007** [comment]
Thanks for the info. I use Terminal especially for colored output and build a wrapper around the Terminal methods. If it is possible to detect the "pipe" I can use std.stdio: writeln instead.
Throwing an exception make sense.

**Comment by adamdruppe** [comment]
Yeah, that's possible, I just need to look it up and write a little code. I'll probably make it a static method so you can call and wrap too. I might also just make the writeln still work in that case, and the other methods can be no-op or throw exception.

If I don't get back to you in a couple days, send me another reminder. I'm doing like 5 things at once this week lol

**Comment by andre2007** [comment]
You allowed me to send you a reminder:)

**Comment by adamdruppe** [comment]
oh and it is a good thing you did, i totally forgot! But I just made it throw on Windows at least, so you can do a try/catch to detect. I'm considering a static function to check or maybe a new ctor that can automatically fallback to simple output in that case too.....

**Comment by adamdruppe** [comment]
I never answered this but `Terminal.stdoutIsTerminal` is the function added you can test before it throws now.
