### ISSUE TITLE
[nanovg] createFont does not return FONS_INVALID if font loading failed

### ISSUE THREAD

**Issue by drug007** [adamdruppe/arsd#147]
ubuntu 17.10, dmd 2.078, arsd-official 2.0.0
```
        auto nvg = nvgCreateContext();

	auto fontname = "NonExistingFont";
	auto fontpath = "../fonts/";

	auto fnt = nvg.createFont(fontname, fontpath); // fnt == 0
```

between, shouldn't FONS_INVALID be FONTS_INVALID?

**Comment by adamdruppe** [comment]
FONS stands for "font stash", it comes from the C bindings.

But just pushed a patch that makes it fall back less aggressively, might work for you now. The way these font config things work is it falls back to more common fonts instead of just outright failing... but the new patch might be better
