### ISSUE TITLE
Package arsd defines no import paths

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#161]
It is only a minor issue, recent dub version throws a warning during compilation:

```Package arsd-official:terminal (configuration "library") defines no import paths, use {"importPaths": [...]} or the default package directory structure to fix this.```

**Comment by adamdruppe** [comment]
This doesn't seem to happen anymore (though dub is so hard to use I find it hard to prove)... gonna close it now since I *think* it is fixed.
