### ISSUE TITLE
Compiling with minigui.d throws warning

### ISSUE THREAD

**Issue by takase1121** [adamdruppe/arsd#162]
When I tried to compile a GUI program with minigui.d, the compiler throws a warning. 
![image](https://user-images.githubusercontent.com/20792268/41412381-6940a56c-7012-11e8-9818-912a03749288.png)
Help will be appreciated.

**Comment by adamdruppe** [comment]
On Thu, Jun 14, 2018 at 05:36:14AM -0700, takase wrote:
> When I tried to compile a GUI program with minigui.d, the compiler throws a warning. 

try rebuilding now from master

But that warning is worthless - it doesn't actually matter and does not indicate an actual bug (actually, in this specific case, it is a habit of mine to prevent bugs, but the compiler doesn't recognize the pattern).

Looks like the build succeeded anyway so no harm done.

**Comment by takase1121** [comment]
Yeah I know the warning won't affect the program but it fails to compile with dub (i forgot to add the ignore warning build option) but everything is fine after i added it. Thanks for attention!
