### ISSUE TITLE
Error drawing images

### ISSUE THREAD

**Issue by Aphexus** [adamdruppe/arsd#170]
glTexImage2D(
			GL_TEXTURE_2D,
			0,
			GL_RGBA,
			_texWidth, // needs to be power of 2
			_texHeight,
			0,
			GL_RGBA,
			GL_UNSIGNED_BYTE,
			data);

		auto gle = glGetError();
		import std.conv :to;
		assert(!gle, "Image error `" ~ to!string(gle)~"`");

error 1282. The image and data seems to be correct so I'm not sure why it is failing.

I'm pretty sure this coded worked before and I coped it all to another project and now can't get it to 
work. Maybe I'm forgetting to initialize something?

Any idea what it might be? I'm simply loading a 263x256 png image.

The code I'm using is basically

	gh.OpenGlTexture oGLimage;	
	TrueColorImage image;

	image = imageFromPng(readPng(Image0)).getAsTrueColorImage;	
	oGLimage = new gh.OpenGlTexture(image);

**Comment by Aphexus** [comment]
Heres the full code

	/// Make a texture from an image.
	this(TrueColorImage from) {
		assert(from.width > 0 && from.height > 0);

		import core.stdc.stdlib;

		_width = from.width;
		_height = from.height;

		this.from = from;

		auto _texWidth = _width;
		auto _texHeight = _height;

		const(ubyte)* data = from.imageData.bytes.ptr;
		bool freeRequired = false;

		// gotta round them to the nearest power of two which means padding the image
		if((_texWidth & (_texWidth - 1)) || (_texHeight & (_texHeight - 1))) {
			_texWidth = nextPowerOfTwo(_texWidth);
			_texHeight = nextPowerOfTwo(_texHeight);

			auto n = cast(ubyte*) calloc(_texWidth * _texHeight * 4,1);
			if(n is null) assert(0);
			scope(failure) free(n);

			auto size = from.width * 4;
			auto advance = _texWidth * 4;
			int at = 0;
			int at2 = 0;
			foreach(y; 0 .. from.height) {
				n[at .. at + size] = from.imageData.bytes[at2 .. at2+ size];
				at += advance;
				at2 += size;
			}

			data = n;
			freeRequired = true;

			// the rest of data will be initialized to zeros automatically which is fine.
		}

		glGenTextures(1, &_tex);
		glBindTexture(GL_TEXTURE_2D, tex);
		//glPixelStorei(eGL.GL_UNPACK_ALIGNMENT, 1); //1: byte alignment

		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
		glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE);
		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP);
		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP);
		

		glTexImage2D(
			GL_TEXTURE_2D,
			0,
			GL_RGBA,
			_texWidth, // needs to be power of 2
			_texHeight,
			0,
			GL_RGBA,
			GL_UNSIGNED_BYTE,
			data);

		auto gle = glGetError();
		import std.conv :to;
		assert(!gle, "Image error `" ~ to!string(gle)~"`");

**Comment by Aphexus** [comment]
I  put glGetError higher up and it too is returning 1282, so this seems to be an error that occurs much earlier but is only caught at this point for some reason...

**Comment by adamdruppe** [comment]
On Sun, Oct 07, 2018 at 03:43:26AM -0700, Aphexus wrote:
> Heres the full code

Looks very similar to my function i have used before except

> 		//glPixelStorei(eGL.GL_UNPACK_ALIGNMENT, 1); //1: byte alignment
> 
> 		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
> 		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
> 		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP);
> 		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP);

these. But the docs say they should work with any opengl version so I doubt it is the problem.

Maybe you didn't initialize something right. I'm not an opengl master, but since the code you have here is really similar to what i have successfully used in the past, that's just my best guess.

> 		assert(!gle, "Image error `" ~ to!string(gle)~"`");

BTW it might help to use gluErrorString to get a better error

can cast it to char* and use fromStringz or just pass it right to printf()

its argument is the error code

**Comment by Aphexus** [comment]
Ok, well, it seems I have to use open GL after the window is created and all that.

I guess only after whatever is initialized can I use the openGL image routines. I guess openGL isn't being initialized  until then. I'll need to create some type of hook that is called after the window is created but before the event loop so I can pre-load all the images.

Thanks, seems it was an issue on my part.

It would be better if the error was something like "OpenGL has not been initialized" rather than "Invalid operation".

Thanks.

**Comment by adamdruppe** [comment]
On Sun, Oct 07, 2018 at 03:32:18PM -0700, Aphexus wrote:
> I guess only after whatever is initialized can I use the openGL image routines. I guess openGL isn't being initialized  until then. I'll need to create some type of hook that is called after the window is created but before the event loop so I can pre-load all the images.

Yeah, I believe that is the case, simpledisplay.d's SimpleWindow has a
visibleForTheFirstTime delegate you can set on a window to do such
initialization work there.

> It would be better if the error was something like "OpenGL has not been initialized" rather than "Invalid operation".

Yeah, the opengl errors aren't great, but not much I can do about that,
they are provided by the system.

**Comment by Aphexus** [comment]
Yeah, I have a wrapper around your code and I had an initialization routine but it was being called before the window was being creating, which I forgot.

Everything seems to be working now, thanks.
