### ISSUE TITLE
http2: Syntax errors 

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#176]
The breaks after goto are superfluous and causing warning (Statement not reachable)

https://github.com/adamdruppe/arsd/blob/18673f0b1bba837e65d48211486059e42e941195/http2.d#L869
https://github.com/adamdruppe/arsd/blob/18673f0b1bba837e65d48211486059e42e941195/http2.d#L897

Also this error is thrown:
Error: function `arsd.http2.SSL_set_fd(SSL*, int)` is not callable using argument types `(SSL*, socket_t)`
cannot pass argument `this.handle()` of type `socket_t` to parameter `int`

**Comment by andre2007** [comment]
Also setting version "without_openssl" causes new errors:
http2.d(474,15): Error: undefined identifier `SslClientSocket`
http2.d(623,19): Error: undefined identifier `SslClientSocket`

**Comment by adamdruppe** [comment]
On Thu, Nov 22, 2018 at 12:54:45AM -0800, andre2007 wrote:
> The breaks after goto are superfluous and causing warning (Statement not reachable)

I seriously loathe that idiotic warning. It makes my code ugly and bug prone.

Just fork the compiler and hack it out of there.

**Comment by adamdruppe** [comment]
On Thu, Nov 22, 2018 at 08:56:59AM +0000, andre2007 wrote:
> Also setting version "without_openssl" causes new errors:
> http2.d(474,15): Error: undefined identifier `SslClientSocket`
> http2.d(623,19): Error: undefined identifier `SslClientSocket`

I couldn't repro that. What are all your compile flags?

**Comment by adamdruppe** [comment]
On Thu, Nov 22, 2018 at 12:54:45AM -0800, andre2007 wrote:
> The breaks after goto are superfluous and causing warning (Statement not reachable)
> Also this error is thrown:
> Error: function `arsd.http2.SSL_set_fd(SSL*, int)` is not callable using argument types `(SSL*, socket_t)`

fixed all

**Comment by andre2007** [comment]
Thank you so much.
What I noticed regarding http2.d, it is quite hard to use it with Dub. By specifying dependency ```arsd-official``` module http2.d is not found. Also specifying dependency ```arsd-official:http2``` does not work. You have to specify dependency ```arsd-official:http```.

The issue is maybe related to the file structure of the repository. I know you do have reasons to have it that way. I wonder whether it is possible to have a git branch "dub" in addition to master. The content of this branch is generated from master on new releases. Maybe a Travis job copy the files in a file structure as dub is expecting it. On code.dlang.org arsd-official would then point to this branch.

I close this issue. Thank you :)

**Comment by adamdruppe** [comment]
On Thu, Nov 22, 2018 at 10:42:42AM -0800, andre2007 wrote:
> What I noticed regarding http2.d, it is quite hard to use it with Dub. By specifying dependency ```arsd-official``` module http2.d is not found. Also specifying dependency ```arsd-official:http2``` does not work. You have to specify dependency ```arsd-official:http```.

Yeah, the package name is http. The module name is arsd.http2. The 2 in it is a major version number and it has been long enough that the old v1 is dead so i dont hold to it anymore.

but use the package http and import arsd.http2
