### ISSUE TITLE
cgi: Warning: Ddoc: Stray '('

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#177]
There are 2 DDoc warnings raised for cgi.d:

```Warning: Ddoc: Stray '('. This may cause incorrect Ddoc output. Use $(LPAREN) instead for unpaired left parentheses.```

The line numbers does not really fit, maybe DMD gets somehow confused
cgi.d(260,1): 
cgi.d(2235,20):

**Comment by adamdruppe** [comment]
On Tue, Dec 04, 2018 at 12:14:15AM -0800, andre2007 wrote:
> ```Warning: Ddoc: Stray '('. This may cause incorrect Ddoc output. Use $(LPAREN) instead for unpaired left parentheses.```

try it now on master

**Comment by andre2007** [comment]
Thanks a lot.

That is very very strange. The 2 warnings caused the dub error: ```Cannot append empty path string.```
With your correction, dub is now able to generate the documentation. I will create a dub issue for this.

Please consider creating a new release:)

**Comment by andre2007** [comment]
https://github.com/dlang/dub/issues/1607

**Comment by adamdruppe** [comment]
On Tue, Dec 04, 2018 at 10:07:28PM -0800, andre2007 wrote:
> With your correction, dub is now able to generate the documentation. I will create a dub issue for this.

So keep in mind that my docs are NOT compatible with ddoc and there
is no promise it will actually work at all, and will almost certainly
not be super pretty.

Might be good enough, but for my docs you should use one of my websites,
either arsd-official.dpldocs.info or the dpldocs.info/arsd.cgi site
(the former link is updated less frequently, but less likely to break
with my bleeding edge doc generation lol)
