### ISSUE TITLE
sqlite.d does not specify libs in package metadata

### ISSUE THREAD

**Issue by SonicFreak94** [adamdruppe/arsd#181]
This is a problem when generating Visual D solutions. It won't add sqlite3.lib to the list of dependencies the generated project and causes the build to fail.

**Comment by adamdruppe** [comment]
With dmd, it just works thanks to pragma(lib)... thinking VD might
be using the dub, so I added it to dub.json. See if that works better.

**Comment by SonicFreak94** [comment]
Sorry I haven't had a chance to test it out. I hope to do that today.

I believe the reason it doesn't work with the generated Visual D project is because it gets places in the .dub folder. The project file's directory is then typically used as the working directory/default lib search path, so the `pragma` fails to load the lib file (which in my case is in the package root dir).

**Comment by SonicFreak94** [comment]
Yep, it now adds the lib file to the list of required libraries. It looks like it's still going to end up searching the project's working directory by default, though (.dub), so this probably ends up being moot. Would probably be easier for me to just add the lib to my `PATH` rather than wrangle dub into cooperating.

**Comment by adamdruppe** [comment]
Yeah, maybe some linker flag could do it too with dub's `lflags-windows` config thing but I don't really know.
