### ISSUE TITLE
[cgi.d] Infinite loop with big headers

### ISSUE THREAD

**Issue by cym13** [adamdruppe/arsd#182]
# Issue
It is possible to craft a header so that `cgi.d` ends up in an infinite loop.

# Details

In `cgi.d` the header is read from `pps.buffer` which can grow arbitrarily long. When looking for the header's end the function locationOf is used:

```d
int locationOf(T)(T[] data, string item) {
	const(ubyte[]) d = cast(const(ubyte[])) data;
	const(ubyte[]) i = cast(const(ubyte[])) item;

	for(int a = 0; a < d.length; a++) {
        // ...
```
If the header is really huge to the point that `d.length > int.max+4` then `a` overflows, wraps arround and the loop never ends. It needs to be more than `int.max+4` because of the early return in case what we are looking for is longer than what's left in the buffer.

# Reproduction

I stumbled on it while reading the code, although I don't think I missed something in the code I don't have a test case to reproduce the issue.

# Fix

I see no benefit for this function to work on `int` so it's likely a bug, I'd work with size_t.max instead and a sanity check, or maybe chunks if you really want to support headers bigger than 4GB.

**Comment by adamdruppe** [comment]
thanks, yeah, this is a minor bug though no header should ever be that
long anyway, it should actually check and enforce that rather than assume.

I'll put some fixes up soon

**Comment by cym13** [comment]
Thank you for fixing it.

The only realy case I could see that happening is a malicious actor wanting to DoS the application. That's a real use case since there are business concerns behind any DoS, but it's definitely not critical and easily fixed.

**Comment by adamdruppe** [comment]
I just pushed a simple check and throw exception in the case.
