### ISSUE TITLE
Cgi.d: Range violation

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#184]
This python script 
```python
http_client = http.client.HTTPConnection('127.0.0.1')
http_client.request('POST', '/compile', open(model_file_path, 'rb'))
http_response = http_client.getresponse()
```

will cause a range violation here
https://github.com/adamdruppe/arsd/blob/15e648f43e91980c3c4c620cf5b18f0d029d5c74/cgi.d#L3651

Stack trace
0x000000014007F3EE in d_arrayboundsp
0x0000000140058FC4 in arsd.cgi.BufferedInputRange.popFront at cgi.d(3651)
0x000000014005A1D6 in arsd.cgi.dechunk at cgi.d(3974)
0x0000000140052F84 in arsd.cgi.Cgi.this at cgi.d(1742)
0x0000000140051C29 in arsd.cgi.Cgi.this at cgi.d(1522)
0x00000001400603F5 in arsd.cgi.doThreadHttpConnection!(arsd.cgi.Cgi, handle).doThreadHttpConnection at cgi.d(3328)
0x0000000140059944 in arsd.cgi.ConnectionThread.run at cgi.d(3831)
0x000000014007CEA2 in void core.thread.Thread.run()
0x00000001400974BD in thread_entryPoint
0x000000006FB31D9F in endthreadex
0x000000006FB31E3B in endthreadex
0x00007FFC8D007E94 in BaseThreadInitThunk
0x00007FFC8D1BA251 in RtlUserThreadStart

**Comment by andre2007** [comment]
Using requests and multipart formdata no exception is thrown:

```python
files = {'file': open(model_file_path, 'rb')}
r = requests.post('http://127.0.0.1/compile', files=files)
```

**Comment by adamdruppe** [comment]
On Fri, Feb 22, 2019 at 03:58:34AM -0800, andre2007 wrote:
> This python script 

what version / dependencies of python is that? it doesn't work on
my box. and what is model_file_path?

i need to know what it is actually sending to the network.

**Comment by andre2007** [comment]
It is python 3.6. A text file with the extension .mo is sent. I use the http module which comes with python 3.6

**Comment by adamdruppe** [comment]
On Fri, Feb 22, 2019 at 06:38:49AM -0800, andre2007 wrote:
> It is python 3.6.

ah python 3 is broken on my box i will have to fix that

> A text file with the extension .mo is sent. I use the http module which comes with python 3.6

What is the file? The range violation is likely caused by a chunked block
being exactly on the read boundary.

though, sending a file directly with POST without a content-type header
is probably wrong anyway, it still shouldn't be range violation... just to
reproduce I will need the exact bytes.

**Comment by adamdruppe** [comment]
so i just guessed about the problem based on teh stack trace

can you grab master and retry your tests? it might work now.

text both the multipart and other thing plz

**Comment by andre2007** [comment]
Thanks a lot, I will have a chance to test it on Monday and will give you feedback.

**Comment by andre2007** [comment]
Thank you!
I can confirm, both cases works fine now.
