### ISSUE TITLE
undefined symbol: _D4arsd3cgi15BasicDataServer25handleLocalConnectionDataMFPSQCfQCd4IoOpiZv

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#185]
With arsd-official 2.2.0 I get on windows (dmd 2.0.84.1 x86_64) and on linux  (dmd 2.083.1) following error:

13:01:48 ../tmp/user.home/.dub/packages/arsd-official-2.2.0/arsd-official/cgi.d:(.text+0x185): undefined reference to `_D4arsd3cgi15BasicDataServer25handleLocalConnectionDataMFPSQCfQCd4IoOpiZv'
13:01:48 collect2: error: ld returned 1 exit status
13:01:48 Error: linker exited with status 1

I build with --force argument and also delete any old packages caches before.

**Comment by adamdruppe** [comment]
maybe i tagged it in the wrong spot, try the new 2.2.1 push i just did

**Comment by andre2007** [comment]
Thanks a lot! I can confirm 2.2.1 works fine.
