### ISSUE TITLE
Terminal: Bad characters are written

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#186]
My application has following check

```
import arsd.terminal;

Terminal* _terminal;

void main()
{
    try
    {
        Terminal terminalInstance = Terminal(ConsoleOutputType.linear);
        ._terminal = &terminalInstance;
    }
    catch (Exception e)
    {
        // Console in pipe mode - not supported by arsd library on Windows,
        // session will switch to stdstdio
    }

    scope (exit)
        ._terminal = null;
}
```

This causes some bad characters on Linux which are visible e.g. in Jenkins or if you pipe it to a file:
```rdmd test.d > 1.txt```

![image](https://user-images.githubusercontent.com/1451047/53620847-b79ba280-3bf4-11e9-9f02-3c808c7e3117.png)

Is this expected? How can I avoid this characters?

**Comment by adamdruppe** [comment]
On Thu, Feb 28, 2019 at 10:36:56PM -0800, andre2007 wrote:
> My application has following check

You are escaping a reference outside scope. That's illegal D code.

The correct check is to query `isatty` first, and if true, use Terminal,
and if not, don't - never take a pointer to an object that goes out
of scope.

**Comment by adamdruppe** [comment]
I added a new static method to detect if it is valid to use Terminal:

https://github.com/adamdruppe/arsd/commit/3bcce8b478848867bf2316847a58a6ec08456b01

**Comment by andre2007** [comment]
Thanks a lot

**Comment by adamdruppe** [comment]
BTW would it be useful to you to make it detect that and still pretend
to output?

I haven't done that before since I don't think it is really good to do
autoamtically - most programs I write need to know if it is full screen
or not - but if it is i might be able to do it.

**Comment by andre2007** [comment]
I am not really sure what you meant with the last comment. 
The luxury solution would be if I could use your library in case it outputs to a terminal and also in case it outputs to a non terminal like a file or Jenkins (in this case no control codes should be written).
Also it should work for windows to. Here writing to a file causes some issues to.

But the current state of your library is sufficient and I can work around mentioned things. I just switch to std.stdio for these cases.
