### ISSUE TITLE
cgi.d: Fails to accept http request if I spawn a worker (std.concurrency)

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#188]
This application (```dmd app.d arsd/cgi.d -version=embedded_httpd```) fails to accept http requests on ```Linux``` because I spawn a worker in shared static this. The application works fine on windows.

```d
import arsd.cgi;
import std.concurrency;
import core.thread : Thread;
import core.time : minutes, seconds;

void main()
{
    cgiMainImpl!handle(["--port", "80"]);
}

void handle(Cgi cgi)
{
    if (cgi.requestMethod == Cgi.RequestMethod.GET && cgi.pathInfo == "/healthcheck")
    {
        cgi.setResponseStatus("200 OK");
        cgi.setResponseContentType("text/plain");
        cgi.write("Hello");
        cgi.close();
    }
    else
        cgi.setResponseStatus("404 File Not Found");
}


void worker()
{
    bool done;
    auto thread = Thread.getThis();
    thread.isDaemon(true);

    while (done != true)
    {
        receiveTimeout(1.seconds, (string[] args) { });
    }
}

private Tid _worker;

shared static this()
{
    _worker = spawn(&worker);
}
```

**Comment by andre2007** [comment]
I just saw by chance ```embedded_httpd``` will use processes on linux while e.g. on windows threads are used.
I will check whether my issue disappear on linux by specifying the threads version.

**Comment by adamdruppe** [comment]
Oh yeah, sorry I forgot to reply to this. You might try `-version=embedded_httpd_threads` on Linux and see if it works.

**Comment by andre2007** [comment]
With ```-version=embedded_httpd_threads``` it also works on Linux.

**Comment by andre2007** [comment]
): now it doesn't compile anymore on Windows (-version=embedded_httpd_threads)

```dmd app.d arsd/cgi.d -version=embedded_httpd_threads```

```
arsd\cgi.d(3329): Error: cannot implicitly convert expression connection.handle() of type socket_t to void*
arsd\cgi.d(3187): Error: template instance `arsd.cgi.doThreadHttpConnection!(Cgi, handle)` error instantiating
app.d(8):        instantiated from here: cgiMainImpl!(handle, Cgi, 5000000L)
```

**Comment by adamdruppe** [comment]
On Thu, Mar 07, 2019 at 07:35:31PM +0000, andre2007 wrote:
> ): now it doesn't compile anymore on Windows (-version=embedded_httpd_threads)

I can't reproduce that... which versions do you have? dmd and cgi.d

**Comment by andre2007** [comment]
I use cgi.d from github master. I use exactly the source code from my initial post and execute command ```dmd app.d arsd/cgi.d -version=embedded_httpd_threads``` on windows. 
My dmd version is ```DMD32 D Compiler v2.084.1```

The issue is caused due to this coding:

https://github.com/adamdruppe/arsd/blob/b3df2871d280514f3dbad8b6d7ad59a7a35e527e/cgi.d#L4489-L4505

On windows if version is ```embedded_httpd```, ```embedded_httpd_threads``` will be used, but this definition will become active
```alias CgiConnectionHandle = SOCKET;```

If you directly specify ```embedded_httpd_threads``` on windows, this definition becomes active
```alias CgiConnectionHandle = HANDLE;```

**Comment by adamdruppe** [comment]
ah ok, i should have used embedded_httpd_threads down there.

fixed, try i now

**Comment by adamdruppe** [comment]
I think this is fixed too - can you confirm and close?

**Comment by andre2007** [comment]
Unfortunately there is a new error

cgi.d from master. Compiled on windows with:
```dmd app.d arsd/cgi.d -version=embedded_httpd_threads```

> C:\Users\pc\Desktop\test>dmd app.d arsd/cgi.d -version=embedded_httpd_threads
> arsd\cgi.d(3150): Error: undefined identifier scheduledJobHandlers
> app.d(8): Error: template instance `arsd.cgi.cgiMainImpl!(handle, Cgi, 5000000L)` error instantiating

**Comment by adamdruppe** [comment]
On Sat, Oct 19, 2019 at 05:17:00AM -0700, andre2007 wrote:
> Unfortunately there is a new error

try it again now i think i just put it under the wrong version

weird it didn't show any error on my box but meh

**Comment by andre2007** [comment]
Thanks, now it works.

You may also be interested in Github Actions. It is a free Github service which allows you to run directly dub on pull request review / merge to master. You can even run it on a matrix (windows/mac os/linux).

In easiest case it is just a yml file with following syntax
```yml
name: DLang

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: mihails-strasuns/setup-dlang@v0
    - name: Build
      run: dub build
    - name: Run tests
      run: dub test
```

**Comment by adamdruppe** [comment]
The weird thing here is I did that test on my computer (the Makefile from yesterday now does linux/windows/mac via cross compilers) but they worked here.

But actually I betcha the real problem is because it is in a template and my test didn't do the template. I'll have to add one for that.
