### ISSUE TITLE
Something wrong with SimpleWindow in 64bits

### ISSUE THREAD

**Issue by MuriloMir** [adamdruppe/arsd#189]
Hi. I have noticed something strange recently. Take a look at the following program:
import arsd.image, arsd.simpledisplay;
void main()
{
SimpleWindow window = new SimpleWindow(1000, 600, "Neuron");
Image core = Image.fromMemoryImage(loadImageFromFile("core.png"));
window.eventLoop(100,
{
	auto p = window.draw();
}
);
}
If I compile it in 32bits(-m32) it runs okay but if I compile it in 64bits(-m64) it crashes. I accidentally discovered a way to bypass it. I just add the line
Image.fromMemoryImage(loadImageFromFile("core.png"));
before creating the SimpleWindow, for some reason doing that solves the problem.
I would like you guys to take a look at it to find out the cause of the problem. It seems there is something incompatible with 64bits and nowadays 64bits is the norm so I need it to work with 64bits as well.

**Comment by adamdruppe** [comment]
Well, I tried your program and the error kinda gives it away:

```
start.S:111: undefined reference to `main'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
```

there is a missing `main` function, since the code is empty :P lol

**Comment by MuriloMir** [comment]
hahahaha, very funny, I accidentally pressed Enter and did not finish the comment, I have edited it and it is now complete.

**Comment by adamdruppe** [comment]
what operating system? what build flags? what is the core.png file? send me all of it

**Comment by MuriloMir** [comment]
I am using Windows 10 64 bits. The only build flags are -i and -m64. core.png is just a .png file with a green hexagon drawn in a blue square using the program Paint.

**Comment by adamdruppe** [comment]
I tried and it works for me. Maybe it is the specific png file you have - can you email it to me or something?

**Comment by MuriloMir** [comment]
Yes, I will attach the file here.
In the project folder there is a folder called arsd with all the files from your library.
I am using DMD version 2.082.0 on Windows 10.
And here is the .png file called neuron.png:
![core](https://user-images.githubusercontent.com/32936161/55374213-07b0a200-54de-11e9-9605-c040b24e2633.png)

**Comment by adamdruppe** [comment]
It still works for me (and sorry for being so slow, work send me to a meeting last week and I have been swamped). I have the same dmd version.

What kind of crash do you get? What details?

**Comment by MuriloMir** [comment]
Well, the window opens but the program becomes unresponsive and then I have to close it forcefully with Windows saying the program isn't responding.

**Comment by adamdruppe** [comment]
With that exact, literal code from your first post?

**Comment by MuriloMir** [comment]
yes, and I have tried it with some other codes too

**Comment by adamdruppe** [comment]
how long does it take to say it is unresponsive?

**Comment by MuriloMir** [comment]
it says it the moment I click anywhere on the window

**Comment by adamdruppe** [comment]
And you don't even draw the image?

**Comment by MuriloMir** [comment]
No, the window remains black, the moment it reaches the .eventLoop() method it stops working.

**Comment by MuriloMir** [comment]
By the way, I am testing the flushGui() function and it isn't working, again the images only appear once I call .eventLoop().

**Comment by MuriloMir** [comment]
Here, this is another code with the exact same problem:

**Comment by MuriloMir** [comment]
Here, this is another code with the exact same problem:
import arsd.simpledisplay, arsd.image;

void main()
{
    auto window = new SimpleWindow;
    auto img = Image.fromMemoryImage(loadImageFromFile("profile.jpg"));
    window.eventLoop(0);
}

If I compile it with dmd codigo -i it works but if I compile it with dmd codigo -m64 -i then it doesn't work. And to be more specific the problem that happens is simple, the moment the window pops up the mouse turns to that blue circle and it closes the window by itself.

**Comment by adamdruppe** [comment]
On Tue, Apr 16, 2019 at 10:31:03PM +0000, Murilo Miranda wrote:
> No, the window remains black, the moment it reaches the .eventLoop() method it stops working.

Well, the code you post never draws the image, so staying black is
correct.

But the not responding thing is weird. I wonder if it is actually
throwing an exception or something from the image.

**Comment by MuriloMir** [comment]
The problem is not that it doesn't draw the image, I myself did not call .draw() in any point. The problem is that it crashes, it simples becomes unresponsive and closes by itself. And that only happens if the line auto img = Image.fromMemoryImage(loadImageFromFile("profile.jpg")); comes after and not before the line auto window = new SimpleWindow; and that whole story is only when compiling with -m64.

**Comment by MuriloMir** [comment]
How do I use the flushGui() function? I tested it here and it doesn't work the way I imagined.

**Comment by adamdruppe** [comment]
On Tue, Apr 16, 2019 at 04:01:47PM -0700, Murilo Miranda wrote:
> How do I use the flushGui() function? I tested it here and it doesn't work the way I imagined.

It doesn't do anything on Windows.

**Comment by adamdruppe** [comment]
On Tue, Apr 16, 2019 at 04:01:24PM -0700, Murilo Miranda wrote:
> The problem is not that it doesn't draw the image

I just have no idea what's going on because all these combinations work fine on my computers.

> whole story is only when compiling with -m64.

do you have visual studio installed on your computer?

**Comment by MuriloMir** [comment]
Okay. Now, I have noticed that when I create a SimpleWindow passing a Image variable as argument it at first displays it as a background but when I call the eventLoop() then it turns black again and I have to redraw the image. Why is that?

**Comment by MuriloMir** [comment]
I do not have visual studio no my computer.

**Comment by adamdruppe** [comment]
That constructor is just for extremely basic use-cases. It is a leftover from the earliest versions of the library that only displayed single frames.

I should probably just remove it.

**Comment by MuriloMir** [comment]
Oh, I understand now. If I were you instead of removing it I would simply rewrite it to leave the image as the background even when the eventLoop() is called. That would make it easier to work with scenarios.

**Comment by adamdruppe** [comment]
On Tue, Apr 16, 2019 at 04:36:33PM -0700, Murilo Miranda wrote:
> I do not have visual studio no my computer.

Maybe that actually explains this. Recent dmd comes with a 64 bit
linker packaged, but if you have VS installed (as I do), it ignores it
and uses the Microsoft linker instead.

So maybe the 64 bit linker is buggy... I will try later.

**Comment by MuriloMir** [comment]
I wish programmers would develop their stuff in a more straight forward way, why should it use the VS linker instead of using its own linker?

**Comment by adamdruppe** [comment]
I confirmed it, the bug is definitely with lld-link.exe.

It works fine with the VS linker, breaks with the llvm linker.

This is probably technically considered a dmd bug.

**Comment by adamdruppe** [comment]
On Tue, Apr 16, 2019 at 06:35:06PM -0700, Murilo Miranda wrote:
> I wish programmers would develop their stuff in a more straight forward way, why should it use the VS linker instead of using its own linker?

The VS linker actually works, its own linker is broken.

People have complained about installing the VS linker though, which
is why dmd now tries to come with its own thing (borrowed from the LLVM
project)... and it is outputting a null function pointer here for some
reason. It is probably dmd outputting subtly wrong code in the object file,
those are notoriously underdocumented.

I suggest you just swap the order of those calls for now to work around it,
or use 32 bit, or install the Microsoft linker.

I also filed a bug with dmd upstream, maybe they can learn more:

https://issues.dlang.org/show_bug.cgi?id=19811

**Comment by andre2007** [comment]
Maybe the upgrade to LLD 8.0.0 will solve the issue
https://github.com/dlang/installer/pull/376

**Comment by adamdruppe** [comment]
Yeah, I tried with dmd nightly and it is fixed there.

So @MuriloMir if you can update your dmd to nightly, or just wait until the next dmd release, this problem should be solved for you.

again, sorry it took so long to figure it out (and the dmd folks said they just fixed it a couple days ago anyway) but I'll hit close now because the they already fixed it, just pending formal release.
