### ISSUE TITLE
Remove binary files from version control

### ISSUE THREAD

**Issue by cup** [adamdruppe/arsd#193]
I noticed you have some binary files in version control:

- https://github.com/adamdruppe/arsd/blob/9dd03c31/libeay32.dll
- https://github.com/adamdruppe/arsd/blob/9dd03c31/libssh2.dll
- https://github.com/adamdruppe/arsd/blob/9dd03c31/libssh2.lib

better place to put these type files is here:

https://github.com/adamdruppe/arsd/releases

**Comment by adamdruppe** [comment]
On Mon, Jun 10, 2019 at 05:01:59PM -0700, Steven Penny wrote:
> better place to put these type files is here:
> 
> https://github.com/adamdruppe/arsd/releases

I don't think you can add random files there.

Those are 3rd party files that are just kinda a pain to get to
work with dmd (historically), so I put it here for easy of discovery for people
who do need them.

**Comment by cup** [comment]
@adamdruppe I just tested on my own repo and both file types are allowed.

**Comment by adamdruppe** [comment]
On Mon, Jun 10, 2019 at 07:30:37PM -0700, Steven Penny wrote:
> @adamdruppe I just tested on my own repo and both file types are allowed.

so how did you do it?

**Comment by cup** [comment]
1. visit https://github.com/adamdruppe/arsd/releases
2. click "Draft a new release"
3. Tag version: hello-world
4. click "Attach binaries"
5. click "Publish release"

**Comment by adamdruppe** [comment]
The way it is works for me.
