### ISSUE TITLE
Uri struct is duplicated

### ISSUE THREAD

**Issue by cup** [adamdruppe/arsd#195]
https://github.com/adamdruppe/arsd/blob/9dd03c3158977038302feb9bb45cc6cd77bb89d5/cgi.d#L2378-L2386
https://github.com/adamdruppe/arsd/blob/9dd03c3158977038302feb9bb45cc6cd77bb89d5/http2.d#L292-L302

should probably leave it in `cgi.d`, then

~~~d
import arsd.cgi;
~~~

or similar

**Comment by adamdruppe** [comment]
On Mon, Jun 10, 2019 at 08:54:53PM -0700, Steven Penny wrote:
> import arsd.cgi;

This increases coupling and decreases module cohesion. That's a cost
I'm not willing to pay.

**Comment by cup** [comment]
the coupling is there regardless. any change to struct in CGI would likely need to be downstreamed to HTTP2, is nothing else but to maintain sanity.

**Comment by adamdruppe** [comment]
On Tue, Jun 11, 2019 at 05:42:55AM -0700, Steven Penny wrote:
> the coupling is there regardless. any change to struct in CGI would likely need to be downstreamed to HTTP2, is nothing else but to maintain sanity.

Maybe, but that's *my* problem. Importing the module makes it the *user*'s
problem.

**Comment by cup** [comment]
Fair enough, but it does create another problem. people can create the struct using either module:

~~~d
import arsd.cgi;
import arsd.http2;
~~~

i know for me at least that was confusing. if you are worried about pulling in all of CGI maybe we could break URL parsing into its own module. thats what Vibe does:

http://vibed.org/api/vibe.inet.url/URL

**Comment by adamdruppe** [comment]
On Tue, Jun 11, 2019 at 06:10:35AM -0700, Steven Penny wrote:
> Fair enough, but it does create another problem. people can create the struct using either module:

Yeah, and that does sometimes bug me - I have a module where I combine them right now.

But it is easy enough to just use import and alias statements to pick the one you want,
or just use the fully-qualified name at the usage point.

> i know for me at least that was confusing. if you are worried about pulling in all of CGI maybe we could break URL parsing into its own module. thats what Vibe does:

Yeah, that's probably the best solution, but it would then be a breaking change and complicate
the dependency tree of both modules. So I don't really wanna do that too.

The copy/paste approach is the best I have so far.

**Comment by andre2007** [comment]
The best solution for URL of course would be to add it to Phobos. But that would be a lot of work.
The functionality of ARSD library is fantastic, I use it in a lot of projects. The drawbacks, are issues with dub, IDEs, even unittests.  The unittests of ARSD run always with the tests of my applications as the source type of the ARSD subPackages is source library.
But the benefits using this library outweighs the issues.

**Comment by adamdruppe** [comment]
The only real problem here is if you are using both at once, and it bugs me a little, but the language can handle it just fine. Closing as won't fix.
