### ISSUE TITLE
dom - statement not reachable

### ISSUE THREAD

**Issue by joelcnz** [adamdruppe/arsd#202]
jyble ~master: building configuration "application"...
../../../.dub/packages/arsd-official-4.0.0/arsd-official/dom.d(3118,3): Warning: statement is not reachable

**Comment by adamdruppe** [comment]
On Sat, Jul 13, 2019 at 05:05:55AM -0700, Joel Christensen wrote:
> jyble ~master: building configuration "application"...
> ../../../.dub/packages/arsd-official-4.0.0/arsd-official/dom.d(3118,3): Warning: statement is not reachable

oh gah while fixing a real bug i accidentally copy/pasted that line

fixed now and tagged 4.0.1

**Comment by andre2007** [comment]
@adamdruppe as your library is well used could you think about adding a build pipeline which e.g. tests the pull requests before they are merged to master? Azure pipelines is free for open source projects and should support testing it on windows and linux.

**Comment by adamdruppe** [comment]
well i do test it, just not with the worthless warnings. I can think of only one or two times ever when these warnings have actually caught a real bug.

but meh maybe i should just use them anyway

**Comment by andre2007** [comment]
That would be really great. I just had a look, Azure Pipelines also supports MacOS.

https://azure.microsoft.com/en-us/services/devops/pipelines/

**Comment by joelcnz** [comment]
Thanks, got it going - whee! (the dom library, that is)
