### ISSUE TITLE
cgi issue with versions 

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#203]
Regarding this forum post (https://forum.dlang.org/post/avrrrntdlgnwjishiohr@forum.dlang.org) I found following issues:

First, the default behavior is different between pure dmd and dub. For dmd the default version is "cgi" while for "dub" the default version is "embedded_httpd" as it is the first entry in the list.

Second issue:
Settings sub configuration "cgi" is not possible as dub.json has an invalid value for versions:
```json
{
    "name": "cgi",
    "targetType": "library",
    "versions": [
        ""
    ]
}
````
...Error: unrecognized switch '-version='
Please change it to "versions":[] or remove it completely.

**Comment by adamdruppe** [comment]
Yeah, the dub users I've talked to tend to want embedded_httpd more than old cgi so I changed the default for them.

I'll just add a dummy version to that cuz I want it to be more clear anyway. pushed.

**Comment by adamdruppe** [comment]
this should be fixed too for a few months
