### ISSUE TITLE
SimpleDisplay: Gl library is forced 

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#207]
https://github.com/adamdruppe/arsd/blob/4b91ff49b5893bc1bd2516f5668bfdac899e2cf0/dub.json#L18

Even by setting sub configuration "without-opengl" there are linker errors: cannot find -lGL and -lGLU,
As they are specified for the whole sub package.

**Comment by adamdruppe** [comment]
is this fixed now? I think so cuz it is moved to the configurations thing

**Comment by andre2007** [comment]
I crashed my test environment (sd card of raspberry pi is corrupted and I need to setup it with a hdd). I will try it after I got it working again.

**Comment by andre2007** [comment]
It is working fine now.
