### ISSUE TITLE
Disable mouse events altogether for Terminal

### ISSUE THREAD

**Issue by drkameleon** [adamdruppe/arsd#213]
I'm using (a slightly modified version of) `arsd.terminal`. But given that mouse events are not working properly on Mac (scroll up/down does nothing + at times, when exiting my app, the whole bash console ends up a mess - with random characters being printed when moving the mouse, etc), I'm thinking of **disabling** them.

How could I go about that?

I'm starting the terminal like this:

```
auto terminal = Terminal(ConsoleOutputType.cellular);
auto getter = new ReplLineGetter(&terminal, "Arturo REPL");
```

`ReplLineGetter` is a simple `LineGetter` subclass.

**Comment by adamdruppe** [comment]
Yeah, the Mac Terminal app is broken until like the most recent version, they didn't follow the standard protocol.

but in any case, if you are modifying the source, the easiest place to make an edit is in the constructor of RealTimeConsoleInput. This is around line 1562 of terminal.d, the code looks like:

                        if(flags & ConsoleInputFlags.mouse) {
                                // basic button press+release notification

Just go ahead and make that `if(false)` to disable it entirely across the whole lib.

You could also pass a custom instance of RealTimeConsoleInput to the getline method of LineGetter, which you can do without modifying the terminal.d source. That method looks like:

        public string getline(RealTimeConsoleInput* input = null) {
                startGettingLine();
                if(input is null) {
                        auto i = RealTimeConsoleInput(terminal, ConsoleInputFlags.raw |
                        ConsoleInputFlags.allInputEvents);
                        while(workOnLine(i.nextEvent())) {}
                } else
                        while(workOnLine(input.nextEvent())) {}
                return finishGettingLine();
        }

If you pass an existing pointer in there, it won't create its own. You could make your own instance with just paste and size events for example, or maybe even just raw. So use

     auto i = RealTimeConsoleInput(terminal, ConsoleInputFlags.raw);

or

     auto i = RealTimeConsoleInput(terminal, ConsoleInputFlags.raw | ConsoleInputFlags.paste | ConsoleInputFlags.size);

to exclude the mouse stuff. Then just pass `&i` to your `getline`, and you can have your subclass method override getline and pass it just like that.

**Comment by drkameleon** [comment]
Adam, thanks a lot! :)

Solved.
