### ISSUE TITLE
variable got is shadowing variable arsd.http2.HttpRequest.advanceConnections.got.

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#226]
Here another warning:

Deprecation: variable got is shadowing variable arsd.http2.HttpRequest.advanceConnections.got. Rename the foreach variable.

https://github.com/adamdruppe/arsd/blob/1f8925cf7ad5522097033b2feab9ab6c835154e9/http2.d#L741

**Comment by adamdruppe** [comment]
my push today should fix all the warnings!
