### ISSUE TITLE
Nanovega: unresolved external symbols

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#228]
The GUI framework [nanogui](http://code.dlang.org/packages/nanogui) uses arsd.nanovega. I adapted the dub.json of nanogui to point to latest arsd-official version 4.1.5 and built the arsd GUI sample.

```
Performing "debug" build using C:\Develop\D\dmd2\windows\bin\dmd.exe for x86_64.
arsd-official:color_base 4.1.5: building configuration "library"...
arsd-official:simpledisplay 4.1.5: building configuration "normal"...
arsd-official:ttf 4.1.5: building configuration "library"...
arsd-official:nanovega 4.1.5: building configuration "library"...
gfm:math 7.0.8: target for configuration "library" is up to date.
derelict-util 3.0.0-beta.2: target for configuration "library" is up to date.
derelict-gl3 2.0.0-beta.8: target for configuration "library" is up to date.
gfm:opengl 7.0.8: target for configuration "library" is up to date.
derelict-sdl2 3.1.0-alpha.4: target for configuration "derelict-sdl2-dynamic" is up to date.
gfm:sdl2 7.0.8: target for configuration "library" is up to date.
nanogui 0.2.1: building configuration "library"...
nanogui-arsd ~master: building configuration "application"...
Linking...
example-arsd.obj : error LNK2019: unresolved external symbol _D4arsd8nanovega30stbi_set_unpremultiply_on_loadFiZv referenced in function _D4arsd8nanovega__T11createImageZQoFPSQBkQBi18NVGcontextinternalAxaAxEQCqQCo12NVGImageFlagXSQDmQDk8NVGImage
example-arsd.obj : error LNK2019: unresolved external symbol _D4arsd8nanovega30stbi_convert_iphone_png_to_rgbFiZv referenced in function _D4arsd8nanovega__T11createImageZQoFPSQBkQBi18NVGcontextinternalAxaAxEQCqQCo12NVGImageFlagXSQDmQDk8NVGImage
example-arsd.obj : error LNK2019: unresolved external symbol _D4arsd8nanovega9stbi_loadFPxaPiQcQeiZPh referenced in function _D4arsd8nanovega__T11createImageZQoFPSQBkQBi18NVGcontextinternalAxaAxEQCqQCo12NVGImageFlagXSQDmQDk8NVGImage
example-arsd.obj : error LNK2019: unresolved external symbol _D4arsd8nanovega15stbi_image_freeFPvZv referenced in function _D4arsd8nanovega__T11createImageZQoFPSQBkQBi18NVGcontextinternalAxaAxEQCqQCo12NVGImageFlagXSQDmQDk8NVGImage
.dub\build\application-debug-windows-x86_64-dmd_2089-40262484D4AED942F0A7F4722D7B5B3A\example-arsd.exe : fatal error LNK1120: 4 unresolved externals
Error: linker exited with status 1120
```

Linker does not find the functions from the static if. I do not really understand why a static if is needed here. If I move the definitions outside the static if, then the nanogui arsd example compilation and linking is fine.

https://github.com/adamdruppe/arsd/blob/449f46307e61b56ccddfb7bda248e7197446294d/nanovega.d#L579-L588

Is this an issue with nanogui or with nanovega?

**Comment by adamdruppe** [comment]
The major package of arsd-official should probably not be used, try with just the nanovega subpackage.

**Comment by andre2007** [comment]
That is exactly the way how it is implemented in nanogui, I just set the newest arsd-official:nanovega version to 4.1.5

**Comment by adamdruppe** [comment]
On Wed, Nov 06, 2019 at 06:08:23AM -0800, andre2007 wrote:
> That is exactly the way how it is implemented in nanogui, I just set the newest arsd-official:nanovega version to 4.1.5

blah te other files are prolly still there then.

the reason for those static if things is it tries to detect optional
libraries automatically for alternative implementations or progressive
enhancement... an dub doesn't play well witht hat

**Comment by adamdruppe** [comment]
I changed my dub.json some more and made version 4.2.0 with a slightly different layout. The examples/arsd in nanovega now compiles and links for me... so try updating that, just make sure in the nanovega fork you also update the dependencies

**Comment by andre2007** [comment]
Thanks a lot, it compiles & links now with optlink on windows but fails for ldd (coff).

It cannot find the core.stdc.math functions which are imported like that nanovega.d:

```
public import core.stdc.math :
  nvg__sqrtf = sqrtf,
  nvg__modf = fmodf,
  nvg__sinf = sinf,
  nvg__cosf = cosf,
  nvg__tanf = tanf,
  nvg__atan2f = atan2f,
  nvg__acosf = acosf,
  nvg__ceilf = ceilf;
```

```
lld-link: error: undefined symbol: sqrtf
>>> referenced by C:\Users\pc\AppData\Local\dub\packages\arsd-official-4.2.0\arsd-official\nanovega.d:1843
>>>               arsd-official_nanovega.lib(nanovega_302_5da.obj):(_D4arsd8nanovega14nvg__normalizeFNbNiNfPfQcZf)
```

If I remember correctly optlink automatically imports some libraries while other linker don't.
I wonder which library (*.lib file) contains the core.stdc.math functions?

**Comment by adamdruppe** [comment]
that's weird, is it just the one function it complains about or others too?

There is a note in the source code

> else version (CRuntime_Microsoft) // fully supported since MSVCRT 12 (VS 2013) only


so maybe it is cuz of that...

**Comment by andre2007** [comment]
It complains about the others too.

**Comment by adamdruppe** [comment]
ok. It is probably just missing the math lib or whatever.

I'll play on my box, can probably hack around it by adding a
libs-windows thing in my file.

**Comment by andre2007** [comment]
I can't reproduce the issue on another windows computer. Everything compiles and links fine (x86_64 COFF). Therefore closing this issue.
Thanks a lot.

**Comment by drug007** [comment]
I reproduce the issue. What the windows way to link to standard math lib?

**Comment by adamdruppe** [comment]
oh i forgot all about this one.... i don't even know the linker command lines on windows for adding stuff.  except adding an explicit .lib on the command line or pragma(lib)...

**Comment by drug007** [comment]
I see) What is the name of the windows standard math library? libm.lib doesn't work

**Comment by adamdruppe** [comment]
On Tue, Mar 03, 2020 at 07:27:54AM -0800, drug007 wrote:
> I see) What is the name of the windows standard math library? libm.lib doesn't work

it might just be "-lm" on the ldc command line.

I just put my Windows laptop away though but if taht doesn't work i'll
play with it again in a little bit.

**Comment by drug007** [comment]
Hmm, that definitely depends on installed libs. I play a bit and link errors have changed, to be continued...

**Comment by drug007** [comment]
I installed Windows SDK and now the link errors like:
```
libcmt.lib(utility_desktop.obj) : error LNK2019: reference to unresolved external symbol __imp_RtlLookupFunctionEntry in function __scrt_fastfail
...
```

**Comment by drug007** [comment]
The problem is caused by (non)installed libraries. Installed Windows SDK and VC++ tools fix the issue.

**Comment by adamdruppe** [comment]
On Tue, Mar 03, 2020 at 08:27:47AM -0800, drug007 wrote:
> The problem is caused by (non)installed libraries. Installed Windows SDK and VC++ tools fix the issue.

Yeah, I suppose so, I just tried it on my wife's computer... but I put
VS 2013 on it a while ago soooo it just worked but I did that so if
that's the solution there we go.
