### ISSUE TITLE
Error: variable `s` is shadowing variable `arsd.cgi.cgiMainImpl!(handle, Cgi, 5000000L).cgiMainImpl.s

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#232]
Could you have a look?

https://github.com/adamdruppe/arsd/blob/d04c6806e3cf4933b92a04798d92189971d86ec7/cgi.d#L3357

https://github.com/adamdruppe/arsd/blob/d04c6806e3cf4933b92a04798d92189971d86ec7/cgi.d#L3380

**Comment by adamdruppe** [comment]
What build flags are you  using? and is this on a linux musl system?

**Comment by adamdruppe** [comment]
or just grab master and try again for me

**Comment by andre2007** [comment]
Thanks, that works. Yes, I am working on Alpine Linux (Musl Lib C)
