### ISSUE TITLE
Is minigui.d thread safe?

### ISSUE THREAD

**Issue by aferust** [adamdruppe/arsd#234]
I am playing around with minigui, and made [this small tweak](https://github.com/aferust/doitlater) .  I am manipulating widgets from another thread, and usually works without any problems. However sometimes it crashes or becomes nonresponsive. I am not sure if this is the reason for it though. Usually gui libs have some helper functions allowing to alter widgets in the main thread but calling them from a thread function (wxwidgets has "CallAfter", javafx has something like runlater). Should I worry about this with minigui?

**Comment by adamdruppe** [comment]
I.... don't know. I never even thought about it, much less tried.

**Comment by aferust** [comment]
Anyway, so far it is doing well, switching between enable/disable would be nice too, for at least text based widgets. I was planning to make a PR but noticed that one must also be aware of win32 stuff along with custom_w that I have no any bg.

**Comment by adamdruppe** [comment]
I did some fixes to this recently and actually used it in a project. You have to use gui objects in the same thread that created them and simpledisplay assumes there is one master gui thread. It provides `runInGuiThread` now so other threads can run code over there when the event loop is idle, and the simplewindow event system works across threads too. So the answers now is basically yes, just make sure you use the runInGuiThread or events if crossing the boundary.
