### ISSUE TITLE
posix problem with cgi.d and embedded_httpd

### ISSUE THREAD

**Issue by pinver** [adamdruppe/arsd#235]
Trying to use current master under macOS, importing cgi.d and using the embedded httpd, I got:
```
dmd -i -version=embedded_httpd  --version=cgi_with_websocket -Isrc -run src/example_cgi.d

src/arsd/cgi.d-mixin-5391(6447): Error: undefined identifier epoll_fd
src/arsd/cgi.d(5105): Error: template instance arsd.cgi.runAddonServer!(BasicDataServerImplementation) error instantiating
src/arsd/cgi.d(3173):        instantiated from here: runSessionServer!()
src/arsd/cgi.d(3154):        instantiated from here: cgiMainImpl!(hello, Cgi, 5000000L)
```

It seems really that `epoll_fd` is defined in `version(linux)`, but not in the `else` ...

I've not studied the code right now for a possible fix, but I just want to pin that in a issue.

**Comment by pinver** [comment]
Oh, well, commenting out the offending line, just works fine, so I'm not sure is that should be moved into the `version(linux)` blocks as, well, `epoll` is linux only, after all ...

**Comment by adamdruppe** [comment]
On Thu, Jan 09, 2020 at 02:16:42PM -0800, pinver wrote:
> Oh, well, commenting out the offending line, just works fine, so I'm not sure is that should be moved into the `version(linux)` blocks as, well, `epoll` is linux only, after all ...

Yeah, I probably just missed a spot while shuffling code around last
time.

if ou can PR it, cool, if not i will tomorrow.

**Comment by adamdruppe** [comment]
actually i think i just fixed it now and had to tag anyway

**Comment by adamdruppe** [comment]
gonna close since it passes my test on the mac build too
