### ISSUE TITLE
cgi.d: undefined identifier UnixAddress

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#238]
I try to get WebSockets running on Windows and facing these 3 issues:

> arsd\cgi.d(1598): Error: undefined identifier UnixAddress
https://github.com/adamdruppe/arsd/blob/1bc81effb2ce2f975e56692df4f9e6d33f95a004/cgi.d#L1598

> arsd\cgi.d(4905): Error: cannot implicitly convert expression msg.realLength of type ulong to uint
https://github.com/adamdruppe/arsd/blob/1bc81effb2ce2f975e56692df4f9e6d33f95a004/cgi.d#L4905

> arsd\cgi.d(4906): Error: cannot implicitly convert expression msg.realLength of type ulong to uint
https://github.com/adamdruppe/arsd/blob/1bc81effb2ce2f975e56692df4f9e6d33f95a004/cgi.d#L4906

**Comment by adamdruppe** [comment]
aaaah im the worst i commited a whole batch without compiling on windows a few days ago

**Comment by adamdruppe** [comment]
pushed and tagged 'v5.2.4'

**Comment by adamdruppe** [comment]
BTW that was to work around a Phobos bug that I think is actually merged but is not in the pending release :(

oh well

**Comment by andre2007** [comment]
Thanks a lot, that solves the issues on windows.
