### ISSUE TITLE
cgi: Succesfully stopping server

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#242]
On a specific request, the server should stop listen and the application should shutdown gracefully.
I use a dummy exception to stop the http server. Is there any better way provided by cgi.d?
I cannot find anything:

```d
class WebsocketServer
{
    void serveForever()
    {
        try
        {
            cgiMainImpl!((cgi){socketHandler(cgi);}, Cgi, defaultMaxContentLength)([]);
        }
        catch(ExitRequestException e)
        {
            trace("Stopped server");
        }
    }

    private void socketHandler(Cgi cgi)
    {
        auto websocket = cgi.acceptWebsocket();
        
        while(websocket.recvAvailable(300.seconds)) 
        {
            auto websocketMessage = websocket.recv();
            if (websocketMessage.opcode == WebSocketOpcode.close) break;

            if (cgi.pathInfo == "/exit")
                throw new ExitRequestException();
            
            // ...
        }
        websocket.close();
    }
}

class ExitRequestException : Exception
{
    @safe pure nothrow this(string file = __FILE__,
            size_t line = __LINE__, Throwable next = null)
    {
        super("ExitRequestException", file, line, next);
    }
}
```

**Comment by adamdruppe** [comment]
There is no function for that. I've been meaning to add one but just never have. One of the tricky parts is that the server may be spread across several processes, so I'd probably want to use a signal (like ctrl+c, but can be sent by function too) to inform them all to quit after the requests they currently have.

For now that exception is perhaps a good way to do it. But keep this issue open, I'll come back to it when I'm caught up on day job work. (I had a furnace failure yesterday and dental mishap earlier in the week so been crazy irl and I'm a couple days behind now.....)

**Comment by adamdruppe** [comment]
lol i was just looking at this and there actually IS a function for that... it is just an instance method on a private object.

gotta think of a way to expose that..... I'm tempted to do an all-new server control api. So instead of calling main per se, you'd do a `new CgiServer` and the quit method can be on that. Can also do things like handle port and host selection in a nicer way than forging command line options to it.

might not be read tonight after all though.....

**Comment by andre2007** [comment]
Thank you a lot for your work on this Adam.

**Comment by andre2007** [comment]
Solved.
