### ISSUE TITLE
Does it need to call ChoosePixelFormat twice?

### ISSUE THREAD

**Issue by johnburton** [adamdruppe/arsd#253]
Very minor issue, if it is in fact one at all, and only detail rather than a bug but is there any reason why simpledisplay calls ChoosePixelFormat in line 8402 when it just got the value in line 8400?

https://github.com/adamdruppe/arsd/blob/master/simpledisplay.d#L8400

**Comment by adamdruppe** [comment]
I probably copy/pasted the line at some point doing error checking and
just mindlessly messed it up.....

**Comment by adamdruppe** [comment]
there removed and nothing broke!
