### ISSUE TITLE
Package logo on dub

### ISSUE THREAD

**Issue by WebFreak001** [adamdruppe/arsd#256]
As this is one of the packages with the highest score I think it would be very nice if arsd had a package logo on the DUB registry. Logos are simply uploaded on the dub registry website.

Designing a logo can be a little bit of a challenge but it will make the dub registry homepage look a lot nicer if more packages have logos.

**Comment by adamdruppe** [comment]
Yeah, I have thought about it before but can't think of a good one.

When I was a wee lad this was my arsd logo http://arsdnet.net/arsdlogo.png but i don't use it anymore cuz like it is kinda lame.

and since it is a collection of random modules there's no one big topic either except maybe a whole library who knows.

so the design is the hard part.

**Comment by WebFreak001** [comment]
what does arsd stand for?

**Comment by adamdruppe** [comment]
On Mon, Jun 08, 2020 at 05:38:17AM -0700, Jan Jurzitza wrote:
> what does arsd stand for?

adam ruppe's software development

my fake company name lol

**Comment by adamdruppe** [comment]
so how ugly is this?

http://arsdnet.net/arsd-module-logo.jpg

my brother's painting "View From Phobos" i also used on the cover of "d cookbook" isn't square so i had to add some space under and combined my old style logo under to fill the gap and kinda tie that in

i put it on dub but might still change it.

BTW dub converted my jpg into a png and made it 5x bigger!!!! ugh, being a scan of a painting this is more suited to jpeg compression. sigh.

**Comment by WebFreak001** [comment]
cool, also logos don't need to be square (they keep aspect ratio)

I would make the text bigger and maybe simplify it a bit because the logo is mostly scaled down to fit in 64x64 or 150x150 boxes

**Comment by adamdruppe** [comment]
eh im gonna close cuz i added something and it is good enough now for me. can always improve later.
