### ISSUE TITLE
terminal.d freezes on `getline` after `moveTo()`

### ISSUE THREAD

**Issue by 0xEAB** [adamdruppe/arsd#259]
```d
auto t = Terminal(ConsoleOutputType.cellular);
t.moveTo(10, 10);
t.getline("Name: "); // doesn't print `Name: ` but freezes
```

Terminal emulator: Tilix
OS: Ubuntu 18.04.5

**Comment by adamdruppe** [comment]
OK, I can reproduce it.

My suspicion is the get current cursor position code is stuck in a loop
blocking for more data that will never come. That friggen function has
been the worst - I *hate* how these query commands are mixed into the
data stream. The Windows way - a dedicated get info function - is so so
so much better.

but i'll check it out.

**Comment by adamdruppe** [comment]
oh it is because 10 is a two digit number. i screwed this up bad, try this commit and see if it passes all your use cases:

https://github.com/adamdruppe/arsd/commit/f22cd2d21b68c3ac1ab198432200b386d290a5c1

**Comment by 0xEAB** [comment]
lgtm

**Comment by 0xEAB** [comment]
thanks
