### ISSUE TITLE
package svg - fail

### ISSUE THREAD

**Issue by joelcnz** [adamdruppe/arsd#260]
Joel-Computer:SpellIt joelchristensen$ dub --version
DUB version 1.22.0, built on Jul  7 2020
Joel-Computer:SpellIt joelchristensen$ dmd --version
DMD64 D Compiler v2.093.0
Copyright (C) 1999-2020 by The D Language Foundation, All Rights Reserved written by Walter BrightJoel-Computer:SpellIt joelchristensen$ dub add arsd-official
Adding dependency arsd-official ~>8.3.0
Joel-Computer:SpellIt joelchristensen$ dub
Failed to find any versions for package svg, referenced by arsd-official 8.3.0

**Comment by adamdruppe** [comment]
argh i missed a colon in the config file

i hate dub.json it is what drives me most nuts about this. it is the
opposite of DRY. shouldn't even exist at all.

pushed and labeled 8.3.1

**Comment by joelcnz** [comment]
That's better, thanks.
