### ISSUE TITLE
ld: warning: directory not found for option '-L/usr/X11/lib'

### ISSUE THREAD

**Issue by joelcnz** [adamdruppe/arsd#261]
Using macOS 10.15.6
With "dependencies": {
				"arsd-official": "~>8.3.1",

Maybe just use sub configurations, idk.

Linking...
ld: warning: directory not found for option '-L/usr/X11/lib'
ld: warning: directory not found for option '-L/usr/X11/lib'
ld: warning: directory not found for option '-L/usr/X11/lib'
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
/Library/D/dmd/bin/dmd failed with exit code 1.

**Comment by adamdruppe** [comment]
Apple removed their X server, you now need to install it separately. I think it will work if you fetch XQuartz from the app store.

I barely support Apple stuff since it deprecates stuff so often....

**Comment by adamdruppe** [comment]
What are you trying to do btw? Does the X server look like a reasonable thing for you?

I've been slowly working on reviving the Cocoa port and you can compile it too with `-version=OSXCocoa -version=allow_unimplemented_features`. But very little of it actually works right now so almost certainly useless to you.

But if there's just a few features needed I might be able to slap them together in shortish time.

**Comment by joelcnz** [comment]
I haven't actually tried using X server. So I don't anything about it really. Having said that, I did try to find XQuartz in App Store, but no. Looks like I can get it from its web site though.

I just have to use sub configurations. Like I should anyway (isn't it called smelly programming to do things like, 'import std;')

Thanks for replying. I've got a bunch of posts, lately, that have no replies. One problem brakes all my Windows Allegro 5 programs since I can't link the lib files.

**Comment by adamdruppe** [comment]
So my libs are actually designed to bring in what is needed as needed when you just have the whole thing on your computer... but dub doesn't support that. So on dub yeah you should use the subpackages. I kinda hate it too especially with how easy it is with plain dmd to incrementally pull stuff in.

but yeah if using dub, there's subpackages for the most common individual modules so you can get them without corrupting the build with stuff you don't need.

What are your other problems btw? I don't really follow other libs that closely and it seems more and more questions as time goes on are esoteric to some library so I don't jump in but I still migt be able to help if you wanna put it here or paste links or whatever.

**Comment by joelcnz** [comment]
Using Windows 10.

In my dub.json file I have:
"lflags" : ["+..\\DAllegro5\\lib\\"],

But I get:
Linking...
lld-link: error: could not open '+..\DAllegro5\lib\': no such file or directory
lld-link: error: could not open 'allegro.lib': no such file or directory
...
lld-link: error: could not open 'allegro_audio.lib': no such file or directory
Error: linker exited with status 1

Of course, I have lib files in there (DAllegro5\lib\ ..). Is there a different switch I can use in my dub file.

It was working on another computer. I'm doing it strait off a flash drive, (I've tried it on computer drive with no difference).

**Comment by joelcnz** [comment]
Now I get undefined errors:

lld-link: error: undefined symbol: al_color_name_to_rgb
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:55
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base9getColourFAyaZS8allegro55color13ALLEGRO_COLOR)

lld-link: error: undefined symbol: al_map_rgb_f
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:58
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base9getColourFAyaZS8allegro55color13ALLEGRO_COLOR)

**Comment by adamdruppe** [comment]
are you also including the allegro_color lib file in your link?

**Comment by joelcnz** [comment]
I got it to stop complaining about the lib files.

**Comment by adamdruppe** [comment]
yay! lol

**Comment by joelcnz** [comment]
Just the undefined errors I mentioned, now.

**Comment by adamdruppe** [comment]
just those two? the docs do say they are part of the allegro_color addon lib so do check that again, otherwise they might actually be C macros instead of formal functions. the "view source" links are broken in the documentation, ugh, still though that's it isn't it: https://github.com/liballeg/allegro5/blob/master/addons/color/color.c#L207

and that's no macro...

idk.

tbh at this point if you can't solve it for real, you could hack it by just defining an `extern(C)` function somewhere in your code with the same name and just an `assert(0);` body.... to appease the linker and get moving forward.

**Comment by joelcnz** [comment]
Not just those two - heaps of them.

**Comment by adamdruppe** [comment]
Can you paste the whole output? There might be a clue hidden in there.

**Comment by joelcnz** [comment]
D:\jpro\dpro2\Windows\Balliters>dub --verbose
Using dub registry url 'https://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
Looking for local package map at C:\Users\nev\AppData\Local\dub\packages\local-packages.json
Looking for local package map at D:\jpro\dpro2\Windows\Balliters\.dub\packages\local-packages.json
Note: Failed to determine version of package balliters at .. Assuming ~master.
Refreshing local packages (refresh existing: false)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
Looking for local package map at C:\Users\nev\AppData\Local\dub\packages\local-packages.json
Looking for local package map at D:\jpro\dpro2\Windows\Balliters\.dub\packages\local-packages.json
  Found dependency allegro 4.0.4+5.2.0
Refreshing local packages (refresh existing: false)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
Looking for local package map at C:\Users\nev\AppData\Local\dub\packages\local-packages.json
Looking for local package map at D:\jpro\dpro2\Windows\Balliters\.dub\packages\local-packages.json
  Found dependency allegro 4.0.4+5.2.0
Generating using build
Configuring dependent balliters, deps:"allegro"
  Configuring dependent allegro, deps:
Performing "debug" build using D:\jpro\dmd2\windows\bin64\dmd.exe for x86_64.
allegro 4.0.4+5.2.0: target for configuration "no-libs" is up to date.
Using existing build in C:\Users\nev\AppData\Local\dub\packages\allegro-4.0.4_5.2.0\allegro\.dub\build\no-libs-debug-windows-x86_64-dmd_2093-0F8A7C412A952CF9C6319EAE06E6FE40\.
Copying target from C:\Users\nev\AppData\Local\dub\packages\allegro-4.0.4_5.2.0\allegro\.dub\build\no-libs-debug-windows-x86_64-dmd_2093-0F8A7C412A952CF9C6319EAE06E6FE40\dallegro5.lib to C:\Users\nev\AppData\Local\dub\packages\allegro-4.0.4_5.2.0\allegro
Target 'D:\jpro\dpro2\Windows\Balliters\.dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.exe' doesn't exist, need rebuild.
balliters ~master: building configuration "application"...
D:\jpro\dmd2\windows\bin64\dmd.exe -m64 -c -of.dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj -debug -g -w -version=Have_balliters -version=Have_allegro -Isource -IC:\Users\nev\AppData\Local\dub\packages\allegro-4.0.4_5.2.0\allegro ..\Jeca\jeca\all.d ..\Jeca\jeca\base.d ..\Jeca\jeca\bmp.d ..\Jeca\jeca\misc.d ..\Jeca\jeca\snd.d ..\Jext\jext\all.d ..\Jext\jext\base.d ..\Jext\jext\letter.d ..\Jext\jext\lettermanager.d source\balliters.d source\base.d source\blets.d source\bletsman.d source\board.d source\display.d source\dotman.d source\fps.d source\game.d source\gameover.d source\help.d source\input.d source\larverbombblow.d source\lazer.d source\lazerbeam.d source\menu.d source\mine.d source\piece.d source\pointer.d source\popup.d source\setup.d source\shield.d source\ship.d source\tkey.d source\unit.d source\unitlist.d source\weakbrickblow.d source\wordsounds.d -vcolumns
Compile time: Go go, military hovercraphs, ships are go!
source\piece.d(16,42): Deprecation: returning this.m_type escapes a reference to parameter this, perhaps annotate with return
source\piece.d(19,40): Deprecation: returning this.m_boardGfx escapes a reference to parameter this, perhaps annotate with return
source\pointer.d(34,4): Deprecation: foreach: loop index implicitly converted from size_t to int
Linking...
D:\jpro\dmd2\windows\bin64\dmd.exe -of.dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.exe .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj C:\Users\nev\AppData\Local\dub\packages\allegro-4.0.4_5.2.0\allegro\.dub\build\no-libs-debug-windows-x86_64-dmd_2093-0F8A7C412A952CF9C6319EAE06E6FE40\dallegro5.lib -L/LIBPATH:..\DAllegro5\lib -m64 -g
lld-link: error: undefined symbol: al_color_name_to_rgb
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:55
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base9getColourFAyaZS8allegro55color13ALLEGRO_COLOR)

lld-link: error: undefined symbol: al_map_rgb_f
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:58
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base9getColourFAyaZS8allegro55color13ALLEGRO_COLOR)

lld-link: error: undefined symbol: al_map_rgb
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:114
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base12ColourStruct11makeColoursMFZv)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:115
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base12ColourStruct11makeColoursMFZv)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:116
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base12ColourStruct11makeColoursMFZv)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:117
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base12ColourStruct11makeColoursMFZv)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:118
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base12ColourStruct11makeColoursMFZv)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:119
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base12ColourStruct11makeColoursMFZv)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:120
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base12ColourStruct11makeColoursMFZv)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:121
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base12ColourStruct11makeColoursMFZv)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:122
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base12ColourStruct11makeColoursMFZv)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:123
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base12ColourStruct11makeColoursMFZv)
>>> referenced 3 more times

lld-link: error: undefined symbol: al_create_event_queue
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:160
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:324
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base10init_inputFZv)

lld-link: error: undefined symbol: al_install_keyboard
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d-mixin-178:178
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_get_keyboard_event_source
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:179
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:325
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base10init_inputFZv)

lld-link: error: undefined symbol: al_register_event_source
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:179
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:187
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:295
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:325
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base10init_inputFZv)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:326
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base10init_inputFZv)

lld-link: error: undefined symbol: al_install_mouse
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d-mixin-186:186
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_get_mouse_event_source
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:187
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_install_audio
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d-mixin-193:193
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_init_acodec_addon
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d-mixin-194:194
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_reserve_samples
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d-mixin-195:195
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_init_image_addon
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:202
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_init_font_addon
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:204
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_init_ttf_addon
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:206
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_init_primitives_addon
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:208
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_set_new_display_flags
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:292
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_create_display
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:294
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: undefined symbol: al_get_display_event_source
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:295
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:326
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base10init_inputFZv)

lld-link: error: undefined symbol: al_hide_mouse_cursor
>>> referenced by D:\jpro\dpro2\Windows\Balliters\..\Jeca\jeca\base.d:299
>>>               .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\balliters.obj:(_D4jeca4base4InitFAAyaiZi)

lld-link: error: too many errors emitted, stopping now (use /errorlimit:0 to see all errors)
Error: linker exited with status 1
FAIL .dub\build\application-debug-windows-x86_64-dmd_2093-6DBCC4520FAB2D793A3ABC227A0541C3\ balliters executable
D:\jpro\dmd2\windows\bin64\dmd.exe failed with exit code 1.

D:\jpro\dpro2\Windows\Balliters>

**Comment by adamdruppe** [comment]
That final command line didn't actually link the libraries.... and this is why:

> allegro 4.0.4+5.2.0: target for configuration "no-libs" is up to date.

It is building the wrong config! looking at the source code here https://github.com/SiegeLord/DAllegro5/blob/master/dub.json there's a subconfig you want to get the libs added to the command.

So, back to your own dub config file, you will have a line like "dependencies": {"allegro": "whatever"}.

After that dependencies section, add: `"subConfigurations": {"allegro": "all-addons"}`

docs: https://dub.pm/package-format-json.html#configurations

or if you are using the other format there's an example here https://dub.pm/package-format-sdl.html#configurations


Then give it a build....

**Comment by joelcnz** [comment]
That got me farther, but I get this error, and I can't find that file (with the others I renamed them - like 'allegro_acodec-5.0.10-md.lib' to just ''allegro_acodec.lib').

lld-link: error: could not open 'allegro_video.lib': no such file or directory
Err

**Comment by adamdruppe** [comment]
blargh maybe that's an addon not included with the download.

I guess an alternative is you could go back to the way it was, delete the subconfiguration, then copy/paste the libs section into your own dub config and just delete the libs that you can live without

```
            "libs": [
                "allegro",
                "allegro_audio",
                "allegro_font",
                "allegro_ttf",
                "allegro_image",
                "allegro_color",
                "allegro_primitives"
            ]
```

maybe like that. I see you've been asking in the issues tab of that repo for a while, im not sure the author really kept up with this at all... you might just want to fork the library too, or find a different one.

**Comment by joelcnz** [comment]
I've spent a lot of time making programs and stuff using allegro with D, including a big game I made (Balliters). I had been using DSFML, until that wouldn't work any more after updating my macOS, and the sound was unstable on Windows. Lately I've been using SDL, and my last program uses Foxid.

Is this right? I get the undefined stuff again.
```
{
    "name": "balliters",
    "targetType": "executable",
    "description": "A Poorly Programmed Production. Presenting: Balliters!",
    "copyright": "Copyright © 2017 none",
    "lflags" : ["/LIBPATH:..\\DAllegro5\\lib"],
	"sourcePaths" : ["source",
                     "../Jeca/jeca",
                     "../Jext/jext"
					 ],
    "dependencies": {
        "allegro": "~>4.0.1+5.2.0"
    },
    "libs": [
        "allegro",
        "allegro_audio",
        "allegro_font",
        "allegro_ttf",
        "allegro_image",
        "allegro_color",
        "allegro_primitives"
    ],
}
```

**Comment by adamdruppe** [comment]
yeah that's what i was thinking... but blargh the dallegro library probably calls some of the other functions in its wrapper and requires all of them. maybe another download would have those codec and video ones.

idk, i feel like we made some progress here but i might not be of much more help. i've never used any of these libraries (the only library code i use regularly are the files in this very repo) so im just completely guessing from general knowledge and a few quick looks at the docs.

it might need a recompile of allegro itself or its extensions, or some modifications to the dallegro library to remove/update code you don't need or something like that.

**Comment by joelcnz** [comment]
Well, thanks for all your help, anyway.
