### ISSUE TITLE
resize handling constructor/"documentation" require openGlOptions passing

### ISSUE THREAD

**Issue by crazymonkyyy** [adamdruppe/arsd#263]
```d
auto window = new SimpleWindow(Size(500, 500), "Event example - simpledisplay.d",OpenGlOptions.no,Resizability.allowResizing);
```
>window resize handling: pass Resizability.allowResizing to the constructor, set a handler on window.windowResized

It needed the opengl options whatever that is to be passed.

**Comment by adamdruppe** [comment]
added an overload so you can swap the order there and it still works
