### ISSUE TITLE
link error: multiple definition of 'NotifyHint'

### ISSUE THREAD

**Issue by mingwugmail** [adamdruppe/arsd#266]
/usr/bin/ld.gold: error: /home//.dub/packages/x11-1.0.21/x11/.dub/build/library-unittest-linux.posix-x86_64-ldc_2093-42C1E92598FFF523DFD2D341F01C19E5/libx11.a(x11.X.o): multiple definition of 'NotifyHint'
/usr/bin/ld.gold: /home//.dub/packages/arsd-official-8.5.3/arsd-official/.dub/build/normal-unittest-linux.posix-x86_64-ldc_2093-30A361E7C83040B9316C05B807FC2322/libarsd-official_simpledisplay.a(arsd.simpledisplay.o): previous definition here
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
/home//project/ldc2-1.23.0-linux-x86_64/bin/ldc2 failed with exit code 1.

**Comment by adamdruppe** [comment]
https://github.com/adamdruppe/arsd/commit/bd3c7ecf35049fbeebda45a9a515f46aedd8e1df#diff-66f7065b8a7a2d3ee65dc3bd188ed3cae2ba9408d3a6b1be34955695e36deb1bL12103

that line there, just changing from const into to enum might be good enough. the value isn't used anyway, it was just part of the original header.

**Comment by mingwugmail** [comment]
yes, change to enum fixed it linking error.
