### ISSUE TITLE
Any minigui code compiled for 64 bit crashes.

### ISSUE THREAD

**Issue by aferust** [adamdruppe/arsd#269]
Yes, it crashes with LDC 1.24.0 on my Win10 computer. --arch=X86 works well. If 64bit is not supported, just ignore and close the issue :)

**Comment by adamdruppe** [comment]
oh dear i see it too, i must have missed some bad cast somewhere.

**Comment by adamdruppe** [comment]
so i saw the crash in wine... then copied it over do my Windows box to
run in the debugger and it is fine there.

**Comment by adamdruppe** [comment]
I think it is solved, a mouse event was needed to trigger the crash...

can you try again with the git master version? (I think you can download the minigui.d file into your source directory even using dub to get master)

**Comment by aferust** [comment]
Yes, I confirm 👍
