### ISSUE TITLE
Minigui: LineEdit password style

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#272]
Could you add the possibility to mask the text in a LineEdit / LabeledLineEdit as password? For win32 this is the ES_PASSWORD style.

https://docs.microsoft.com/en-us/windows/win32/controls/use-a-single-line--edit-control

**Comment by adamdruppe** [comment]
Yeah, that's fairly simple, I'll add it to my todo list.

I'm in the middle of rewriting the whole text engine on linux right now which will make that a lot easier to do there too... but I'll prolly push the Windows thing possibly as early as tomorrow.

**Comment by adamdruppe** [comment]
I had to do it as a separate class which I don't love but Windows doesn't let you change that style after construction...

**Comment by andre2007** [comment]
Thanks a lot Adam.
