### ISSUE TITLE
WebSocket: Socket select error: An invalid argument was supplied

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#276]
WebSocket client is raising error `Socket select error: An invalid argument was supplied`.

I reduced it to this coding:
(While it says version 9.1.2, it is actually `master`)

``` d
/+ dub.sdl:
    name "app"
    dependency "arsd-official:http" version="9.1.2"
+/

import http2;

void main()
{
    auto ws = new WebSocket(Uri("ws://localhost:8765"));
    ws.connect();
    WebSocket.eventLoop();
}
```

Python:

``` python
import asyncio
import websockets

async def hello(websocket, path):
    name = await websocket.recv()
    print(f"< {name}")
    greeting = f"Hello {name}!"
    await websocket.send(greeting)
    print(f"> {greeting}")

start_server = websockets.serve(hello, "localhost", 8765)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

**Comment by adamdruppe** [comment]
I betcha it is just the connection timing out since it never sends. Phobos doesn't detect Windows timeouts right. That seems to be what I'm seeing on Wine, lemme try my laptop too.

You compiling for Windows 64 bit?

**Comment by andre2007** [comment]
Yes, compiling for windows x86_64.

One observation: onOpen and onClose is called fine (writeln debug) if there is no data sent back from server to client.

In case there is data, the error is thrown after onOpen is called.

**Comment by adamdruppe** [comment]
I think I just found it, I handled timeout Unix style with a direct retry, but on Windows a timeout requires the ReadSet to be reconstructed. Just pushed to master, see if it works well for you now.

**Comment by adamdruppe** [comment]
I also changed the openssl load because my test rig didn't have the dlls, it should work better now but lmk if that broke too.

**Comment by andre2007** [comment]
Thanks a lot :)
This solved the issue.
