### ISSUE TITLE
simpledisplay.d: blitting from spritesheets?

### ISSUE THREAD

**Issue by quickfur** [adamdruppe/arsd#279]
The current API, AFAICT, only supports blitting an entire Sprite or Image to the window. Meaning that if I have a whole bunch of sprites, I have to create separate Sprite objects for them, and may run into system limits. Is there a way to add support for blitting sub-rectangles of a Sprite to the window instead?  So I could load a spritesheet, say, and render sprites by blitting sprites from subrectangles of the sheet. That way I can greatly save on the number of Sprite objects I have to create.

**Comment by adamdruppe** [comment]
Yeah those are pretty easy to add on, even in a backward compatible way. Both the Windows and X functions support it, I just never forwarded the necessary arguments.

**Comment by adamdruppe** [comment]
I'll prolly do it tonight when back on my desktop if you don't beat me to it.

**Comment by adamdruppe** [comment]
well other random stuff included in the commit too but the master now has args for image upper left and size, lemme know if that works for you

**Comment by quickfur** [comment]
Awesome, works very nicely.  Thanks for the prompt response!
