### ISSUE TITLE
simpledisplay.d noproperty premultiply for type arsd.color.Color

### ISSUE THREAD

**Issue by DustinMorado** [adamdruppe/arsd#286]
When I try to compile any of the simpledisplay.d examples I get the following error:
```
$ dmd color.d simpledisplay.d example.d
simpledisplay.d(12541): Error: no property `premultiply` for type `arsd.color.Color`
simpledisplay.d(12535): Error: no property `unPremultiply` for type `arsd.color.Color`
simpledisplay.d(12562): Error: undefined identifier `unPremultiplyRgba`
simpledisplay.d(12577): Error: undefined identifier `premultiplyBgra`
```
Even just a simple import errors:
``` D
import arsd.simpledisplay;
import std.stdio : writeln;

void main() {
    writeln("hello");
}
```

This is on Ubuntu 20.04.1 / with DMD 2.096.1 and also on Mac OSX compiled with `dmd -L=-L/usr/X11/lib color.d simpledisplay.d example.d`

**Comment by adamdruppe** [comment]
oops i forgot to commit a file when i pushed just a sec

**Comment by adamdruppe** [comment]
aaah i did commit it, i just didn't git push it.

try it now.

**Comment by DustinMorado** [comment]
Yes works. Thank you for the very fast correction!
