### ISSUE TITLE
cgi.d: specify a unix socket for fastcgi

### ISSUE THREAD

**Issue by Ssamm45** [adamdruppe/arsd#315]
It looks like you can pass `--listening-host unix:filename` to cgi.d when in `embedden_httpd` mode but it doesn't work that way when in `fastcgi` mode.

It looks like you can just pass `filename` to `FCGX_OpenSocket` to have it open as unix socket and if you pass host:port it opens it as a tcp socket.

**Comment by adamdruppe** [comment]
oh cool i didn't know it could do that. I just committed a change without testing, if it works let me know.

**Comment by Ssamm45** [comment]
I'll test it when I get home from work

**Comment by Ssamm45** [comment]
I tested the code, and after a typo fix it worked fine

**Comment by adamdruppe** [comment]
sweet. thanks again!
