### ISSUE TITLE
libssl library not found

### ISSUE THREAD

**Issue by zorael** [adamdruppe/arsd#321]
Windows 10, ldc 1.28.1, arsd-official 10.8.1.

When I try to download a page using `http2`, it throws an exception about missing SSL libraries despite them being installed (from https://slproweb.com/products/Win32OpenSSL.html).

If I uncomment the lines attempting to load `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` (and add a missing `is null` check for the latter), it works.

https://github.com/adamdruppe/arsd/blob/77c11d27a5bdf9afa5322ac6d374da7367af46d5/http2.d#L3072-L3077

**Comment by adamdruppe** [comment]
ok yeah i was experimenting with those just yesterday but wasn't sure they improved anything, i'll uncomment them again. been having trouble with certs this week.

**Comment by adamdruppe** [comment]
Can you test it with the new master? I put it on x86_64 with a null check fallback. I will test on my system too and confirm the fallback is all good.

**Comment by zorael** [comment]
Yes, now it seems to work (at least my minor test case does).

**Comment by adamdruppe** [comment]
ok good, it works on my computer too. this is always a bit awkward, openssl on windows is a bit of a pain.

**Comment by zorael** [comment]
Thanks!

**Comment by adamdruppe** [comment]
will be included in 10.8.3 tagged later today or tomorrow
