### ISSUE TITLE
Empty-body POSTs don't get a Content-Length header

### ISSUE THREAD

**Issue by zorael** [adamdruppe/arsd#328]
I was attempting to access the Google API[1], which at one point requires a POST request with some query params (where the body can be left empty) to get an OAuth access token.

```d
auto client = new HttpClient;
const url = "https://oauth2.googleapis.com/token?client_id=[stuff]&client_secret=[stuff]&code=[stuff]&grant_type=authorization_code&redirect_uri=[stuff]"
// ...
auto req = client.request(Uri(url), HttpVerb.POST);
auto res = req.waitForCompletion();
```

```xml
<!DOCTYPE html>                                                                            
<html lang=en>                                                                             
  <meta charset=utf-8>                                                                                                                                                                 
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">      
  <title>Error 411 (Length Required)!!1</title>                                                                                                                                        
  <style> [...]
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>411.</b> <ins>That’s an error.</ins>
  <p>POST requests require a <code>Content-length</code> header.  <ins>That’s all we know.</ins>
```

I could work around it by passing a dummy body `ubyte[]` with just `"{}"`, or by manually setting a `Content-Length: 0` header.

```d
auto req = client.request(Uri(url), HttpVerb.POST);
req.requestParameters.headers = [ "Content-Length: 0" ];
auto res = req.waitForCompletion();
```

Should empty-body POSTs get a `Content-Length` too, or am I doing it wrong? Should I expect to have to work around it in these cases?

[1]: https://developers.google.com/identity/protocols/oauth2/native-app

**Comment by adamdruppe** [comment]
I'd have to double check the spec but it is probably my bug. I have

                if(requestParameters.bodyData.length)


And it should probably instead be if the request is a POST or PUT or PATCH.... so this was jsut my shortcut cuz I wouldn't set things otherwise.

**Comment by adamdruppe** [comment]
test it with the master now plz. you can see in the commit it was an easy patch

**Comment by zorael** [comment]
Yes, it seems to work now. Thanks!

**Comment by adamdruppe** [comment]
excellent.
