### ISSUE TITLE
database.d: Change suggestion: Change Row.rows from string[] to Variant[]

### ISSUE THREAD

**Issue by vabenil** [adamdruppe/arsd#340]
Currently after a query is done the values of the fields of each row are converted to string. This however doesn't take into consideration the null type. in D `null == ""` returns true, so if you have a string field it's impossible to differentiate if said field is `null` or just empty in the database. Which is an important differentiation to make.

**Comment by adamdruppe** [comment]
> in D null == "" returns true,

But `str is null` and `str == ""` are two different things.

Though yes, I want to change this anyway - i want to get away from Variant and string - but you should be able to detect it with the `is null` test.

**Comment by vabenil** [comment]
Oh, I didn't know about `str is null` I only tried "str == null". It should be okay then. I will close this then.
