### ISSUE TITLE
Bug in WebSocket close method if supply reason argument

### ISSUE THREAD

**Issue by CoderNate** [adamdruppe/arsd#356]
This is a minor thing because most people probably never use the `code` or the `reason` but it looks like the `code` is currently ignored instead of being prepended to the `reason` when forming `data`.

https://github.com/adamdruppe/arsd/blob/975e3526569c1a743a1d467f1ff73c79e45da347/http2.d#L4882

**Comment by adamdruppe** [comment]
oh yeah i didn't read that part of the spec closely enough. looks easy enough to add, done now

**Comment by CoderNate** [comment]
Nice!  I haven't read the spec but just looking at an example of an implementation it seems that either the data array should be empty or it should begin with a valid binary-encoded code and I'm not sure that `0` is a valid code.  If a code is included in `data` maybe the default should be 1000 (normal closure).

**Comment by adamdruppe** [comment]
oh yeah ill change that that makes sense

**Comment by adamdruppe** [comment]
this was released a while ago so gonna close now
