### ISSUE TITLE
Minigui: How to develop a generic input dialog

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#358]
I would like to have a generic input dialog, which looks like this:

![image](https://user-images.githubusercontent.com/1451047/215189481-34639f5b-5620-4bbe-8df7-5401818e885d.png)

It can be called like this
``` d
void addFishSpecies()
{
    string input;
    if (InputDialog.getInput(this, "New species", "Enter species", input))
    {
	// Do s.th.
    }
}
```

The idea is, the method only returns when the user clicks on OK or cancel or closes the input window with X. If the user pressed the OK button, the method result is `true` otherwise `false`. The actual text he entered is passed using the out variable "input".

I am not really sure, whether I can achieve this behavior with Minigui. This is my current state:

``` d
class InputDialog : Window
{
	private Widget _parent;
	private LineEdit _lineEdit;

	this(Widget parent, string title, string inputText)
	{
		super(title, 250, 100);
		_parent = parent;
		auto staticLayout = new StaticLayout(this);

		auto btnOk= new Button("OK", staticLayout);
		with (btnOk)
		{
			x = 10; y = 70; width = 80; height = 22;
		}
		btnOk.addWhenTriggered({
			_parent.enabled = true;
		});

		auto btnCancel= new Button("Cancel", staticLayout);
		with (btnCancel)
		{
			x = 100; y = 70; width = 80; height = 22;
		}
		btnCancel.addWhenTriggered({
			_parent.enabled = true;
		});

		with (new TextLabel(inputText, TextAlignment.Left, staticLayout))
		{
			x = 10;	y = 10; width = 100; height = 20;
		}

		_lineEdit = new LineEdit(staticLayout);
		with (_lineEdit)
		{
			x = 10; y = 40; width = 140; height = 22;
		}
	}

	static bool getInput(Widget parent, string title, string inputText, out string input)
	{
		parent.enabled = false;
		InputDialog dialog = new InputDialog(parent, title, inputText);
		
		dialog.show();
		return false;
	}
}

void enabled(Widget w, bool e) {
        import core.sys.windows.windows;
        if(w.hwnd)
                EnableWindow(w.hwnd, e);

        foreach(child; w.children)
                child.enabled = e;
}
```

The idea is, during the user enters text into the Input dialog, the main window should be disabled. 
Is this somehow possible?

**Comment by adamdruppe** [comment]
I still have very little support for disabling things, since I hate it when programs do that.

I'd also see if you can use a callback instead of the direct return from your dialog too. You can  

```
module example;
import arsd.minigui;
struct NewSpecies {
        string EnterSpecies;
}

void main() {
        auto window = new Window;
     // display this on click or whatever
        dialog((NewSpecies ns) {
                // use ns.EnterSpecies
        });
        window.loop;
}
```

And it works right now, the lib can generate a dialog from a struct definition.


But if you really wanted to return... you could make this function:

```
	static bool getInput(Widget parent, string title, string inputText, out string input)
	{
		parent.enabled = false;
		InputDialog dialog = new InputDialog(parent, title, inputText);
		
		dialog.show();

                dialog.loop(); // THIS LINE IS ADDED

		return false;
	}
```

Wait for the dialog to exit before returning and if you're on the newer tagged versions, the `dialog.loop();` function can do that by adding `dialog.loop();` before returning, see the thing above. That will run the loop in-place until the dialog window is closed. You can then check your variables (make sure you have the ok and cancel button handlers set some flags you can return to indicate if it was cancelled, for example) and return to carry on the rest of the program.

Combining that with your enabled/disabled function you already have and I think it will do what you want.

**Comment by andre2007** [comment]
Thank you so much Adam. Yes, I know, you do not like disabling elements :)
Maybe there is another workaround. If class Window would provide an event OnDeactivate. This event is  triggered when a window loses the focus and another window of the application gets the focus.

With this event I would be able to set the focus again to the InputDialog when the user clicks on the main window. It has the same effects without disabling elements;)

The counterpart of event OnDeactivate is OnActivate. This event is triggered when a window receives the focus. With these 2 new events other interesting use cases could also be solved.

**Comment by adamdruppe** [comment]
Do the FocusEvent and BlurEvents not trigger on windows? I don't remember if I set them there. But in any case adding the activate/deactivate events it is probably good.

But btw I did add a disable method a while ago too but it isn't recursive like yours.

http://arsd-official.dpldocs.info/arsd.minigui.Widget.enabled.2.html
http://arsd-official.dpldocs.info/source/arsd.minigui.d.html#L509

**Comment by andre2007** [comment]
Thank you Adam. I really missed the "dialog" function, this make thing so much easier.

Actually, neither the `enabled` function from coding above works, nor the Widget.enabled function. The issue is, although I am running the application on Windows, the `hwnd` is null.

``` d
import std;
import arsd.minigui;

class FishingWindow : MainWindow
{
	this()
	{	
            super("text", 600, 400);
	}
}

void main() 
{
    writeln("UsingCustomWidgets: ", UsingCustomWidgets);
    writeln("UsingWin32Widgets: ", UsingWin32Widgets);
    
    auto window = new FishingWindow();
    writeln("Window hwnd: ", window.hwnd);
    window.loop();
}
```

This coding used arsd master and has the output:
> C:\Users\Andre\Desktop\dsamples>dmd -i -run app.d
> UsingCustomWidgets: false
> UsingWin32Widgets: true
> Window hwnd: null


I checked also the "FocusEvent" and "BlurEvent". I added them to my window and while changing the focus between different childs of my window, these events are triggered too (and of course focusing on childs elements of the second window). Therefore these events can be use also, but in contrast to "OnActivate" / "OnDeactivate" the user coding needs to check, whether really the window parent has changed by looking through the parent hierarchy.

**Comment by adamdruppe** [comment]
oooh yeah hwnd is only set it the control is itself backed by a thing, like TextEdit and friends use a Windows control. The Window class actually puts it in a member called... `win.impl.hwnd` i think. I should probably clean up that api a bit.

But yeah adding a new event for when the whole window loses/gains activation is reasonable, the native events have something for that, i just never wrapped it. I'll add to my list.

**Comment by andre2007** [comment]
Thanks, this solves all my issues.
