### ISSUE TITLE
[simpleaudio] problem compiling with ldc2 under linux

### ISSUE THREAD

**Issue by TheZipCreator** [adamdruppe/arsd#359]
I'm trying to compile arsd.simpleaudio with ldc2/dub on linux and I'm getting the following errors:

```
Performing "debug" build using /home/z/things/compilers/ldc2/bin/ldc2 for x86_64.
arsd-official:simpleaudio 10.9.8: building configuration "library"...
/home/z/things/compilers/ldc2/bin/../import/core/sys/posix/sys/types.d(685,11): Error: undefined identifier `c_ulong`
/home/z/things/compilers/ldc2/bin/../import/core/sys/posix/sys/types.d(661,40): Error: undefined identifier `__SIZEOF_PTHREAD_MUTEX_T`
/home/z/things/compilers/ldc2/bin/../import/core/sys/posix/sys/types.d(662,16): Error: undefined identifier `c_long`
/home/z/things/compilers/ldc2/bin/../import/core/thread/threadbase.d(85,23): Error: template instance `core.internal.traits.classInstanceAlignment!(Mutex)` error instantiating
/home/z/things/compilers/ldc2/bin/ldc2 failed with exit code 1.
```

Not sure if this is an ldc2 bug or a simpleaudio bug.

**Comment by adamdruppe** [comment]
It is a compiler regression bug:

https://issues.dlang.org/show_bug.cgi?id=23595

With a possible fix not merged:

https://github.com/dlang/dmd/pull/14826


You can work around it by changing the order of imports in a all-at-once build. I don't know if dub will let you do that but maybe editing the file to import something else first will trick it.

**Comment by TheZipCreator** [comment]
ah. I've moved it into my project instead of importing it as a dependency and now I get this error instead, which may actually be a problem with simpleaudio.d:
```
Performing "debug" build using /home/z/things/compilers/ldc2/bin/ldc2 for x86_64.
bloqq ~master: building configuration "application"...
Linking...
/usr/bin/ld: .dub/build/application-debug-linux.posix-x86_64-ldc_v1.30.0-5E1DB52313F78E46745920055EEB0576/bloqq.o: in function `silence_alsa_messages':
/home/z/code/d/bloqq/source/arsd/simpleaudio.d:3119: undefined reference to `snd_lib_error_set_handler'
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
/home/z/things/compilers/ldc2/bin/ldc2 failed with exit code 1.
```

**Comment by adamdruppe** [comment]
Looks like you didn't add the -lasound library (which the file does automatically when built with a good build system, but dub ignores it... so you have to repeat yourself and add `"libs":["asound"]` to the config file).

**Comment by TheZipCreator** [comment]
yep that worked. still kind of annoying that I need to put `simpleaudio` into my actual project instead of just adding it as a dependency, but hey what can you do. at least it works now.

**Comment by adamdruppe** [comment]
hopefully they'll have the compiler bug fixed soon. i might also be able to work around it in the source with some hack... just pushed something that includes it.

just i have a lot of big changes pending and don't want to tag. i just accidentally committed 200 more lines than i meant to there but fixing it is too much of a hassle

commit history is a lot of work lol
