### ISSUE TITLE
Postgres linking error in Windows

### ISSUE THREAD

**Issue by AlexanderZhirov** [adamdruppe/arsd#364]
Adam, hi! The library cannot be attached when compiling the project in Windows. In Linux, linking is successful with your library. In Windows, I've already tried a bunch of [methods](https://forum.dlang.org/post/wcefhswdizpaaliqiesz@forum.dlang.org).

[This](https://forum.dlang.org/post/trqde9$pte$1@digitalmars.com) solution works, but it doesn't work with your library.

https://github.com/adamdruppe/arsd/blob/bd524763fcd8789f6cf070c35c39e38c1e642bf7/postgres.d#L15

![изображение](https://user-images.githubusercontent.com/37277056/216927930-fdbd9421-8327-45a2-a67d-4f216d354a9e.png)

![изображение](https://user-images.githubusercontent.com/37277056/216928214-d2b52347-9bef-4bfe-9a38-cd388efbfd36.png)

**Comment by adamdruppe** [comment]
try it w/ that commit linked

**Comment by AlexanderZhirov** [comment]
> try it w/ that commit linked

Everything works! Thank you very much!
