### ISSUE TITLE
Get sorted result in Postgres

### ISSUE THREAD

**Issue by AlexanderZhirov** [adamdruppe/arsd#365]
Is it possible to add sorting when getting the result? `asc` and `desc` do not affect the query result.

**Comment by adamdruppe** [comment]
What is your query? This is a standard sql thing so must be something in there you missed...

**Comment by AlexanderZhirov** [comment]
> What is your query? This is a standard sql thing so must be something in there you missed...

Here's an example. I set the sorting by field, but the sorting does not affect the final result.

![изображение](https://user-images.githubusercontent.com/37277056/218981725-25aec67a-6951-43f4-b1ce-2caf7f40d9a4.png)

**Comment by AlexanderZhirov** [comment]
I think the problem is here `row.toAA()`

**Comment by adamdruppe** [comment]
Why is that row.toAA there anyway? Looks like you don't need it at all and yes, D's AAs are not sorted so.... just don't that and things will work better..

You can `foreach(key, value; row)` without converting to an AA at all.

**Comment by AlexanderZhirov** [comment]
> You can `foreach(key, value; row)` without converting to an AA at all.

Yes, thanks. Otherwise, I was thinking of using an associative array for my needs.
