### ISSUE TITLE
Deprecation warnings with dmd 2.103.0 in cgi.d

### ISSUE THREAD

**Issue by abraunegg** [adamdruppe/arsd#378]
As reported here: https://github.com/abraunegg/onedrive/issues/2363 

```
src/arsd/cgi.d-mixin-7156(7163): Deprecation: `traits(isVirtualFunction)` is deprecated. Use `traits(isVirtualMethod)` instead
src/arsd/cgi.d-mixin-7156(7163): Deprecation: `traits(isVirtualFunction)` is deprecated. Use `traits(isVirtualMethod)` instead
```

The version of `cgi.d` that is included in onedrive is https://github.com/adamdruppe/arsd/commit/78b8e30cb9c4a9c8be0bb7eee82203779ba08d07

**Comment by adamdruppe** [comment]
easy change, they do (almost) the same thing, someone just decided to rename the function upstream.

I'm in the middle of a bit of a breaking change right now though, gonna add the requirement to have the `core.d` file added to the build going forward. Easy change really, get both of them and build together and it should work but the core.d file randomly doesn't build rn, it won't stabilize till next month.

I just made the change in master and it builds right now, so you can take the two cgi.d and core.d files and it ought to work and then updating the two of them together going forward should let you keep up with all my planned changes.

Or you can edit the copy you have and just find/replace `isVirtualFunction` with `isVirtualMethod` and everything will work that way too.

Or I could do a git branch off the commit you have and cherry pick in the fix that way, then keep up a little LTS branch thing, just I know I'll forget to update it, but then when you ping me that'll remind me and it can be something we keep building without the second file.

**Comment by abraunegg** [comment]
> Or you can edit the copy you have and just find/replace `isVirtualFunction` with `isVirtualMethod` and everything will work that way too.

No problem - will probably take the file version from https://github.com/adamdruppe/arsd/commit/680003ae8750a202d0d156abe4120031587d8b2e and then update that locally and see how that goes as this appears to be the easiest path forward at this point in time.

**Comment by abraunegg** [comment]
verified doing the above with compiling dmd 2.103.0 & older combinations, no issue.
