### ISSUE TITLE
terminal: support more colors (all the colors?)

### ISSUE THREAD

**Issue by ernest-bruce** [adamdruppe/arsd#379]
could use custom colors for background and foreground?
. by this i mean that, in addition to the color constants, i would appreciate the ability to specify colors using the 0..255 range for red, gree, blue

**Comment by adamdruppe** [comment]
this function does that:

http://arsd-official.dpldocs.info/arsd.terminal.Terminal.setTrueColor.html

**Comment by ernest-bruce** [comment]
oh, wow!
. that was quick!

i *just* discovered it and was preparing what to say about it here (i have been learning about each symbol of the Terminal struct in the past couple of hours)
. i also saw that the terminal may not support all the colors (my web search and your code comments prepared me for that eventuality)
. but i had to find out for myself:

	RGB orange; 
	orange.r=0; orange.g=128; orange.b=128;
	terminal.setTrueColor(orange, orange);

instead of orange, Terminal (macOS) displays cyan

when i use
         terminal.color(Color.blue, Color.blue);
i get blue

seems like my all·the·colors dream has been shattered by the infrastructure

<img width="150" alt="blue" src="https://user-images.githubusercontent.com/6908514/230095406-66718e58-5bea-4ab4-8547-89f86936f15b.png">
<img width="110" alt="not_orange" src="https://user-images.githubusercontent.com/6908514/230095412-75cbd46a-34b1-412d-8e0e-f34fca2526a3.png">

**Comment by adamdruppe** [comment]
Orange is a combination of red and green, not green and blue.

The standard definition for orange is:

RGB(255,165,0)

which might work

**Comment by ernest-bruce** [comment]
omg!
. it does work

this is important for me because i am working on an English·parsing tool that highlights sentence structure
. color is the main mechanism through which i plan on showing parts of speech and sentence components to people

also, orange is my favorite color

thank you very much, Mr Ruppe!

**Comment by ernest-bruce** [comment]
<img width="101" alt="Screen Shot 2023-04-05 at 14 50 05" src="https://user-images.githubusercontent.com/6908514/230220000-afdf45b4-80be-41e2-8a68-90924967b4bb.png">

this led me astraty:
<img width="368" alt="Screen Shot 2023-04-05 at 14 50 55" src="https://user-images.githubusercontent.com/6908514/230220076-fb20bf24-85c0-4291-9589-2b622f561c33.png">
