### ISSUE TITLE
GL 3 failed to load

### ISSUE THREAD

**Issue by EasyLian** [adamdruppe/arsd#381]
10.9.7+    
win 11 22621.1555
10.9.6 normal

**Comment by adamdruppe** [comment]
what program are you using?

**Comment by EasyLian** [comment]
10.9.7+    
win 11 pro 22H2 22621.1555

I used the examples in the document. Everything was normal in 10.9.6, and errors will be reported in 10.9.7 and later.
[https://arsd-official.dpldocs.info/v10.9.9/arsd.nanovega.html](url)

**Comment by adamdruppe** [comment]
ok yeah i think i fixed that on master already but i haven't tagged it for dub.

It was a missing setAsCurrentOpenGlContext call


https://github.com/adamdruppe/arsd/commit/0b145ed3b53bf849adf9bb85a14b6f1e231b9fc3

that commit patches it

**Comment by EasyLian** [comment]
OK.

**Comment by adamdruppe** [comment]
You able to aply that or do you need a release? I've been avoiding tagging since I'm in the middle of a somewhat major change but I can cherry pick into a number if you need it.

**Comment by adamdruppe** [comment]
I did a v10.9.10 hotfix released for this and a couple other small issues.
