### ISSUE TITLE
jsvar.d(737): Error: cannot implicitly convert expression (this._payload._array.length) of type ulong to int

### ISSUE THREAD

**Issue by timotheecour** [adamdruppe/arsd#39]
It can be fixed it by inserting to!int

how come you didn't have this problem ? maybe you were on 32 bits? (I'm on OSX 64bits).

Also, wondering why use int in the 1st place (instead  of ptrdiff_t maybe); 
and why not throw instead of truncating:

```
if(e1 > _payload._array.length)
e1 = _payload._array.length.to!int;
```

**Comment by adamdruppe** [comment]
Closing since this is so old now... jsvar has gotten even looser than it used to be, but there is also `version=jsvar_throw` to make it more strict and throw on a bunch of illegal operations like we talked about here.
