### ISSUE TITLE
Cursor keeps blinking after exit

### ISSUE THREAD

**Issue by VPanteleev-S7** [adamdruppe/arsd#393]
This happens in urxvt.

Before state: cursor in an unblinking block cursor.

Running this program:
```d
void main()
{
	import arsd.terminal;
	auto t = Terminal(ConsoleOutputType.linear);
	t.cursor = TerminalCursor.insert;
}
```

causes the cursor to change to a blinking block cursor.

Generally I try to eliminate all blinking or animating UI elements in the software I use as I find them highly distracting for some reason. It would be nice if arsd would not change the blinking property of the cursor on exit.

Note: I am not a user of this library, only a user of a program which uses this library, so I have little control over the program's preference to use `TerminalCursor.insert`.

Thanks!

**Comment by adamdruppe** [comment]
the destructor resets the terminal cursor to code 0


CSI Ps SP q
          Set cursor style (DECSCUSR), VT520.
            Ps = 0  ⇒  blinking block.
            Ps = 1  ⇒  blinking block (default).
            Ps = 2  ⇒  steady block.
            Ps = 3  ⇒  blinking underline.
            Ps = 4  ⇒  steady underline.
            Ps = 5  ⇒  blinking bar, xterm.
            Ps = 6  ⇒  steady bar, xterm.



I suppose I could change it to 2. I don't think there's any reliable way to save/restore the previous setting so it kinda has to guess something unless you know a better way.


Note that in urxvt, you can ctrl+middle click to bring up a menu to disable the blink (option cursorBlink near the top) to at least ease your pain in the mean time.

**Comment by VPanteleev-S7** [comment]
> I suppose I could change it to 2.

Yes, 2 works.

> I don't think there's any reliable way to save/restore the previous setting so it kinda has to guess something unless you know a better way.

I found this commit in vim:

https://github.com/vim/vim/commit/ce1c32780a7d0ae5110eab627fcbfd4a11e5eb52

but I have no idea what control sequences it's using due to its abstractions.

> Note that in urxvt, you can ctrl+middle click to bring up a menu to disable the blink (option cursorBlink near the top) to at least ease your pain in the mean time.

Amazing, I did not know that. Thank you!

**Comment by adamdruppe** [comment]
i think i we can close this since it is default changed and released now
