### ISSUE TITLE
add a arsd directory

### ISSUE THREAD

**Issue by timotheecour** [adamdruppe/arsd#40]
why not organize your project as follows:
misc-stuff-including-D-programming-language-web-stuff/arsd/files.d
instead of:
misc-stuff-including-D-programming-language-web-stuff/files.d

that way people who clone your repo the usual way can just use it as -Imisc-stuff-including-D-programming-language-web-stuff/
(currently it requires adding a symlink)

**Comment by adamdruppe** [comment]
I changed the top level modules a couple years ago, I now agree it was a huge mistake to do top level names. But I won't add the folder since I already have one here and if you download a zip, it makes one for you too. So if git cloning, I just suggest you:

```
mkdir arsd
cd arsd
git clone .....
```
