### ISSUE TITLE
arsd.script Unable to handle Unicode escape characters

### ISSUE THREAD

**Issue by sdvcn** [adamdruppe/arsd#421]
```
auto v1 = `D Programming Language \u00b7 GitHub`;
```

Unable to process script files with Unicode escape characters in text 

```
script.d(841): 1: Unknown escape char u
```

**Comment by adamdruppe** [comment]
Yeah this is something I never implemented. Pretty easy to add though so maybe i will... there done in the master now

**Comment by adamdruppe** [comment]
so note that the backtick string does NOT support escapes, this si by design, it is a what-you-see-is-what-you-get string from D. But double quote ones do:

```
> auto v1 = `D Programming Language \u00b7 GitHub`;
D Programming Language \u00b7 GitHub
> auto v1 = "D Programming Language \u00b7 GitHub";
D Programming Language · GitHub
`

so like that

**Comment by sdvcn** [comment]
I understand your answer, this issue is triggered when reading the file.
