### ISSUE TITLE
Error in core.d when building on freebsd

### ISSUE THREAD

**Issue by lenoil98** [adamdruppe/arsd#426]
The below error occurs:

arsd-official:core 11.4.2: building configuration "library"...
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4212,10): Error: function `core.sys.freebsd.sys.event.EV_SET(kevent_t* kevp, ulong, short, ushort, uint, long, void*, ulong[4])` is not callable using argument types `(kevent_t*, int, int, int, int, int, void*)`
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4212,10):        too few arguments, expected 8, got 7
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4916,10): Error: function `core.sys.freebsd.sys.event.EV_SET(kevent_t* kevp, ulong, short, ushort, uint, long, void*, ulong[4])` is not callable using argument types `(kevent_t*, int, int, int, int, int, void*)`
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4916,10):        too few arguments, expected 8, got 7
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4926,10): Error: function `core.sys.freebsd.sys.event.EV_SET(kevent_t* kevp, ulong, short, ushort, uint, long, void*, ulong[4])` is not callable using argument types `(kevent_t*, int, int, int, int, int, void*)`
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4926,10):        too few arguments, expected 8, got 7
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4936,10): Error: function `core.sys.freebsd.sys.event.EV_SET(kevent_t* kevp, ulong, short, ushort, uint, long, void*, ulong[4])` is not callable using argument types `(kevent_t*, int, int, int, int, int, void*)`
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4936,10):        too few arguments, expected 8, got 7
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4971,10): Error: function `core.sys.freebsd.sys.event.EV_SET(kevent_t* kevp, ulong, short, ushort, uint, long, void*, ulong[4])` is not callable using argument types `(kevent_t*, int, int, int, int, int, typeof(null))`
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4971,10):        too few arguments, expected 8, got 7
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4973,10): Error: function `core.sys.freebsd.sys.event.EV_SET(kevent_t* kevp, ulong, short, ushort, uint, long, void*, ulong[4])` is not callable using argument types `(kevent_t*, int, int, int, int, int, typeof(null))`
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4973,10):        too few arguments, expected 8, got 7
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4977,10): Error: function `core.sys.freebsd.sys.event.EV_SET(kevent_t* kevp, ulong, short, ushort, uint, long, void*, ulong[4])` is not callable using argument types `(kevent_t*, int, int, int, int, int, void*)`
.dub/packages/arsd-official-11.4.2/arsd-official/core.d(4977,10):        too few arguments, expected 8, got 7
/usr/local/bin/ldc2 failed with exit code 1.

**Comment by adamdruppe** [comment]
what compiler version do you have? i tested on freebsd like a year ago and it worked then but maybe things changed

**Comment by lenoil98** [comment]
I'm using LDC 1.32.0

**Comment by adamdruppe** [comment]
give master a try i think that commit will fix it

**Comment by lenoil98** [comment]
Issue solved.
