### ISSUE TITLE
A few typo's in core.d

### ISSUE THREAD

**Issue by wilsonk** [adamdruppe/arsd#433]
Hey Adam,

Just looking through the code in core.d and noticed that there are 7 spots where Schedulable is typo'd to Scheduable (around lines 4550). Just thought I would let you know, in case someone (including you ;) ) runs a search on the proper spelling and the typos don't come up.

**Comment by adamdruppe** [comment]
golly, blame my auto-complete lol, i typo it once then duplicate every time i use it.

thx tho ill fix it in the next push. some day i need to actually finish all the rest of this stuff so it is legit usable, lol in all the places i use this module's event loop function i ignore all its own i/o things in favor of just registering the old stuff in it. some day. some. day.

**Comment by adamdruppe** [comment]
fixed now. but yeah you can see where i typed it out again like in the subclass' new name i did it right so def auto complete to blame!

**Comment by wilsonk** [comment]
Lol, yep that darn auto complete! Happens on my phone all the time, that is for sure ;)
