### ISSUE TITLE
HTTP2 building failed

### ISSUE THREAD

**Issue by cyrusmsk** [adamdruppe/arsd#447]
M1 macOS if I'm trying to build simple code with subConfig "without_openssl" it raises an error:
Building arsd-official:http 11.4.2: building configuration [without_openssl]
../../../../.dub/packages/arsd-official/11.4.2/arsd-official/http2.d(5845,5): Error: undefined identifier `X509_STORE_CTX`

**Comment by adamdruppe** [comment]
that build mode is obsolete, there's no reason to use it anymore as the openssl is checked at runtime

**Comment by cyrusmsk** [comment]
Thanks Adam. I will use normal build
