### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by zek** [adamdruppe/arsd#45]
in scgi:

auto manager = new ListeningConnectionManager(listeningPort(4000));

must be

auto manager = new ListeningConnectionManager(listeningPort(4000), &doThreadHttpConnection!(Cgi, handler));

netman.d doesn't have windows version. I tried to use httpd.d but it needs netman :)

In curl line 68: I think you must change std.md5 to std.digest.md. It is deprecated.

 embedded_httpd_processes is just  for linux . Can you do it for windows?

**Comment by adamdruppe** [comment]
the old netman has been replaced so time to close (5 years later lol)
