### ISSUE TITLE
Double Buffering quirk

### ISSUE THREAD

**Issue by 0xEAB** [adamdruppe/arsd#459]
The following program exhibits different behavior on my systems.

```d
import arsd.simpledisplay;

void main() {
	auto window = new SimpleWindow(Size(320, 240), "BufferThingy", Resizability.fixedSize, OpenGlOptions.yes);
	bool toDo = true;

	window.redrawOpenGlScene = delegate() {
		if (toDo) {
			glClearColor(1, 0, 0, 1); // red
			glClear(GL_COLOR_BUFFER_BIT);
			window.swapOpenGlBuffers();

			glClearColor(0, 0, 1, 1); // blue
			glClear(GL_COLOR_BUFFER_BIT);
			window.swapOpenGlBuffers();

			toDo = false;
		}
	};

	window.eventLoop(1000, () => window.redrawOpenGlSceneSoon());
}
```

### What is it supposed to do?

- Blink red and blue (frame by frame)?
- Display red only.
- Display blue only.

#### My results

- On my Windows 11 machine it blinks red and blue.
- On Linux with X11 (same computer) it’s red only.
- Wine on Linux with X11 it displays red only.

**Comment by 0xEAB** [comment]
Further ways to alter the outcome:
```d
window.useGLFinish = false;
window.vsync = false;
```

With `useGLFinish = false` it blinks on X11 as long as the timer is about faster than the framerate.
With `vsync = false` and `useGLFinish = false` it changes color at a very slow interval (with a fast timer).

**Comment by adamdruppe** [comment]
we can close now right? cuz the glx man page says this is undefined behavior anyway.

might add a note to my docs just to be clear though

**Comment by 0xEAB** [comment]
I’d say, you go ahead and close once you’ve added your note.
Thanks for your help.

**Comment by adamdruppe** [comment]
https://github.com/adamdruppe/arsd/commit/eaf60b41011c7d44412098ed48068fafa8ffd5aa
