### ISSUE TITLE
minigui: DropdownSelection won't stay open

### ISSUE THREAD

**Issue by whitebyte** [adamdruppe/arsd#469]
It opens on mousedown but closes on mouseup, so it stays open only as long as mouse button pressed. Is it intendend behavior? 

Also it has no select/hover effect.

This is on Linux, maybe on Win it works ok

**Comment by adamdruppe** [comment]
yeah this behavior sucks, it dates back to one of the first ones i wrote and never updated it. maybe i can see about it today

**Comment by adamdruppe** [comment]
it also needs capability to scroll and search

**Comment by adamdruppe** [comment]
arrow keys should also be usable here and on radio buttons (a drop down selection and a list of radio buttons are basically the same thing)

**Comment by adamdruppe** [comment]
well there i think this is good enough pushing to master now
