### ISSUE TITLE
mssql.d :How to Insert a wstring?  And sqlException not work

### ISSUE THREAD

**Issue by FrankLIKE** [adamdruppe/arsd#62]
db.query("INSERT INTO [mytable]([name)VALUES('namevalue')");
if the namevalue  comes from wstring.I get string by toMBS fuction, but it not work,and not get the sqlException.
Thank you.

**Comment by adamdruppe** [comment]
On Thu, Jan 15, 2015 at 07:36:03AM -0800, FrankLIKE wrote:
> if the namevalue  comes from wstring.I get string by toMBS fuction, but it not work,and not get the sqlException.

I would say just convert it to a string with

import std.conv;

to!string(your_wstring);

That's not the most efficient but I'm pretty sure it would work.

**Comment by FrankLIKE** [comment]
Thank you.

**Comment by FrankLIKE** [comment]
toMBS function work ok,it can let the wstring in mssql db display ok.
to!string(wstring) can dispaly ok on gui,but not ok in mssql db.

**Comment by zafer06** [comment]
Hi Adam,

Why "get data" gives the error? Can you help?

```d
import std.stdio;
import arsd.mssql;

void main()
{
    writeln("MSSQL Connection Test");

    auto db = new MsSql("Driver={SQL Server Native Client 11.0};Server=127.0.0.1;Database=test;Uid=test;Pwd=test;");
    ResultSet resultSet = db.query("SELECT * FROM CustomerCard");

    foreach(line; resultSet) 
    {
        writefln("LogicalRef: %s  -- Code: %s", line[0], line["CODE"]);
    }
}
```

```js
...
...
LogicalRef: 120  -- Code: 120 10 564
LogicalRef: 121  -- Code: 120 10 563
LogicalRef: 122  -- Code: 120 10 562
LogicalRef: 123  -- Code: 120 10 561
LogicalRef: 124  -- Code: 120 10 560
LogicalRef: 125  -- Code: 120 10 559
LogicalRef: 126  -- Code: 120 10 558
LogicalRef: 127  -- Code: 120 10 557
arsd.database.DatabaseException@arsd\mssql.d(160): get data:      
                                                                  
                                                                  
----------------
0x00403B2F
0x004039AA
0x0040211B
0x0040E842
0x0040E817
0x0040E72F
0x0040350F
0x76AC919F in BaseThreadInitThunk
0x76FFB54F in RtlInitializeExceptionChain
0x76FFB51A in RtlInitializeExceptionChain
```

**Comment by adamdruppe** [comment]
On Thu, Mar 26, 2015 at 09:32:52AM -0700, Zafer �elenk wrote:
> Why "get data" gives the error? Can you help?

It might be returning SQL_SUCCESS_WITH_DATA, my check there i think is
too broad.

Try changing line 159 to something like plain 

```
SQLGetData(statement, cast(ushort)(i+1), SQL_CHAR, buf.ptr, 255, &ptr);
//if(SQLGetData(statement, cast(ushort)(i+1), SQL_CHAR, buf.ptr, 255, &ptr) != SQL_SUCCESS) 
//throw new DatabaseException("get data: " ~ getSQLError(SQL_HANDLE_STMT, statement)); 
```


So removing the error checking. Then see if it works. If it does, we
should be able to make it

```
auto returned = SQLGetData(statement, cast(ushort)(i+1), SQL_CHAR, buf.ptr, 255, &ptr);
if(returned != SQL_SUCCESS && returned != SQL_SUCCESS_WITH_INFO)
	throw new DatabaseException("get data: " ~ getSQLError(SQL_HANDLE_STMT, statement)); 
```

And hopefully that will work. I don't have a MS SQL server up right
now so can't test it myself but this is my hunch.

**Comment by zafer06** [comment]
```sql
SQLGetData(statement, cast(ushort)(i+1), SQL_CHAR, buf.ptr, 255, &ptr); 
--if(SQLGetData(statement, cast(ushort)(i+1), SQL_CHAR, buf.ptr, 255, &ptr) != SQL_SUCCESS) 
--throw new DatabaseException("get data: " ~ getSQLError(SQL_HANDLE_STMT, statement));
``` 
Yes it works this way. But just bought the first 83 rows of the table?
