### ISSUE TITLE
32/64 bit problems - inspect and script

### ISSUE THREAD

**Issue by Laeeth** [adamdruppe/arsd#69]
on 64 bit arch linux:

inspect.d(255): Error: cannot implicitly convert expression (_aaLen(inspecting._object()._properties)) of type ulong to int
script.d(608): Error: cannot implicitly convert expression (pos + 1LU) of type ulong to int

 works if you just stick to!int on end

**Comment by adamdruppe** [comment]
On Sat, Aug 15, 2015 at 12:40:14PM -0700, Laeeth Isharc wrote:
>  works if you just stick to!int on end

fixed. I also pushed my other inspect thing, i'm working
on a json to struct converter thing.

I so often forget to try a 64 bit build and prefer int to
size_t (it is signed which rox) but that needs a cast.

**Comment by Laeeth** [comment]
Thanks, Adam. Signed size_t (ssize_t) should be in library.
