### ISSUE TITLE
enum Key not defined with version=OSXCocoa 

### ISSUE THREAD

**Issue by 9il** [adamdruppe/arsd#73]
```
../../../../.dub/packages/arsd-official-1.0.1/simpledisplay.d(1743,6): Error: undefined identifier 'Key', did you mean variable 'key'?
```

**Comment by adamdruppe** [comment]
version=OSXCocoa hasn't been updated for years and is way behind
the interface now. (I never actually had a Mac available to me
until recently.)

I intend to update it in the next few months, but right now Cocoa
is really an unsupported platform.

**Comment by adamdruppe** [comment]
dmd is FINALLY getting decent objective-C support so I will probably revisit this soon, but for now gonna close it (i know, 3 years later)
