### ISSUE TITLE
querySelector does not work with xml namespaces

### ISSUE THREAD

**Issue by NVolcz** [adamdruppe/arsd#74]
example:
XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<capec:Attack_Pattern_Catalog xmlns:capec="http://capec.mitre.org/capec-2" ...>
   <capec:Views>
....
```

Code:
```
auto var = document.querySelector("capec:Attack_Pattern_Catalog");
```

**Comment by adamdruppe** [comment]
On Sun, Jan 31, 2016 at 04:33:01AM -0800, NVolcz wrote:
> auto var = documentquerySelector("capec:Attack_Pattern_Catalog");

try

auto var = documentquerySelector("capec\\:Attack_Pattern_Catalog");


Notice the escaped :. querySelector uses the colon as a special syntax
character, it separates a pseudoclass (like :first-child) so it needs to
be escaped to match the namespace colon.
