### ISSUE TITLE
compile cgi.d and get some errors

### ISSUE THREAD

**Issue by mzfhhhh** [adamdruppe/arsd#75]
arsd\cgi.d(318): Error: immutable field 'port' initialization is not allowed in loops or after labels
arsd\cgi.d(321): Error: immutable field 'referrer' initialization is not allowed in loops or after labels
arsd\cgi.d(324): Error: immutable field 'remoteAddress' initialization is not allowed in loops or after labels
arsd\cgi.d(327): Error: immutable field 'userAgent' initialization is not allowed in loops or after labels
arsd\cgi.d(370): Error: immutable field 'requestMethod' initialization is not allowed in loops or after labels
arsd\cgi.d(372): Error: immutable field 'requestMethod' initialization is not allowed in loops or after labels
arsd\cgi.d(376): Error: immutable field 'requestUri' initialization is not allowed in loops or after labels
arsd\cgi.d(383): Error: immutable field 'queryString' initialization is not allowed in loops or after labels
arsd\cgi.d(416): Error: immutable field 'queryString' initialized multiple times
arsd\cgi.d(485): Error: immutable field 'pathInfo' initialized multiple times
arsd\cgi.d(487): Error: immutable field 'requestUri' initialized multiple times
arsd\cgi.d(1170): Error: immutable field 'requestMethod' initialization is not allowed in loops or after labels
arsd\cgi.d(1171): Error: immutable field 'requestUri' initialization is not allowed in loops or after labels
arsd\cgi.d(1173): Error: immutable field 'scriptName' initialization is not allowed in loops or after labels
arsd\cgi.d(1177): Error: immutable field 'queryString' initialization is not allowed in loops or after labels
arsd\cgi.d(1179): Error: immutable field 'pathInfo' initialization is not allowed in loops or after labels
arsd\cgi.d(1181): Error: immutable field 'queryString' initialization is not allowed in loops or after labels
arsd\cgi.d(1182): Error: immutable field 'pathInfo' initialization is not allowed in loops or after labels
arsd\cgi.d(1185): Error: cannot modify immutable expression _get
arsd\cgi.d(1187): Error: immutable field 'getArray' initialization is not allowed in loops or after labels

**Comment by adamdruppe** [comment]
On Fri, Feb 26, 2016 at 10:50:56PM -0800, mzfhhhh wrote:
> arsd\cgi.d(318): Error: immutable field 'port' initialization is not allowed in loops or after labels

What version of the compiler do you have and what switches are
you using to build?

**Comment by mzfhhhh** [comment]
dmd 2.070
dmd app.d cgi.d
```d
import arsd.cgi;

// Instead of writing your own main(), you should write a function
// that takes a Cgi param, and use mixin GenericMain
// for maximum compatibility with different web servers.
void hello(Cgi cgi) {
	cgi.write("Hello, world!");
}

mixin GenericMain!hello;
```
```
cgi.d(188): Deprecation: module std.c.windows.windows is deprecated - Import core.sys.windows.windows instead
cgi.d(316): Error: immutable field 'port' initialization is not allowed in loops or after labels
cgi.d(319): Error: immutable field 'referrer' initialization is not allowed in loops or after labels
cgi.d(322): Error: immutable field 'remoteAddress' initialization is not allowed in loops or after labels
cgi.d(325): Error: immutable field 'userAgent' initialization is not allowed in loops or after labels
cgi.d(328): Error: immutable field 'authorization' initialization is not allowed in loops or after labels
cgi.d(331): Error: immutable field 'authorization' initialized multiple times
cgi.d(334): Error: immutable field 'origin' initialization is not allowed in loops or after labels
cgi.d(337): Error: immutable field 'accept' initialization is not allowed in loops or after labels
cgi.d(340): Error: immutable field 'lastEventId' initialization is not allowed in loops or after labels
cgi.d(344): Error: immutable field 'https' initialization is not allowed in loops or after labels
cgi.d(356): Error: immutable field 'host' initialization is not allowed in loops or after labels
cgi.d(368): Error: immutable field 'requestMethod' initialization is not allowed in loops or after labels
cgi.d(370): Error: immutable field 'requestMethod' initialization is not allowed in loops or after labels
cgi.d(374): Error: immutable field 'requestUri' initialization is not allowed in loops or after labels
cgi.d(378): Error: immutable field 'pathInfo' initialization is not allowed in loops or after labels
cgi.d(380): Error: immutable field 'pathInfo' initialization is not allowed in loops or after labels
cgi.d(381): Error: immutable field 'queryString' initialization is not allowed in loops or after labels
cgi.d(405): Error: immutable field 'queryString' initialized multiple times
cgi.d(436): Deprecation: function std.process.getenv is deprecated - Please use environment.opIndex or environment.get instead
cgi.d(436): Deprecation: function std.process.getenv is deprecated - Please use environment.opIndex or environment.get instead
cgi.d(474): Error: immutable field 'pathInfo' initialized multiple times
cgi.d(476): Error: immutable field 'requestUri' initialized multiple times
```

**Comment by adamdruppe** [comment]
Make sure you have the newest version of cgi.d (you can download it from this github), the line numbers don't match up and I think you are seeing something from a few months ago.

**Comment by mzfhhhh** [comment]
yes,i use "dub fetch arsd" and then get the old version.

now,i get the code from github .it's compile ok now.
thanks.

**Comment by adamdruppe** [comment]
On Sat, Feb 27, 2016 at 06:39:26AM -0800, mzfhhhh wrote:
> yes,i use "dub fetch arsd" and then get the old version.

yeah dub looks for tags which don't work well because i work on individual
files rather than the repo as a whole.

**Comment by adamdruppe** [comment]
I updated the git tag so hopefully dub will start getting the new version now.
