### ISSUE TITLE
compile error: cgi.d with -version=fastcgi 

### ISSUE THREAD

**Issue by mzfhhhh** [adamdruppe/arsd#76]
```
Error 42: Symbol Undefined _FCGX_Accept
Error 42: Symbol Undefined _FCGX_Accept_r
......
File Not Found fcgi.lib
```

**Comment by adamdruppe** [comment]
(sorry for the slow reply, I've been busy lately)

On Sun, Feb 28, 2016 at 10:16:09PM -0800, mzfhhhh wrote:
> ```
> Error 42: Symbol Undefined _FCGX_Accept
> Error 42: Symbol Undefined _FCGX_Accept_r
> ......
> File Not Found fcgi.lib

FastCGI mode depends on an external C library available from
fastcgi.com's API/libraries download section.

You need to compile and install it separately to use that.


On Windows, it is a bit of a pain due to the whole dmc requirement,
you might prefer to use one of the self-contained options: cgi, scgi,
or embedded_httpd.

**Comment by adamdruppe** [comment]
I'm gonna close because it works if you have the C library installed.
