### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by nin-jin** [adamdruppe/arsd#77]
```
.\dub\packages\arsd-master\arsd\simpledisplay.d(1979,7): Warning: instead of C-style syntax, use D-style syntax 'byte[32] key_vector'
.\dub\packages\arsd-master\arsd\simpledisplay.d(2242,8): Warning: instead of C-style syntax, use D-style syntax 'byte[20] b'
.\dub\packages\arsd-master\arsd\simpledisplay.d(2243,9): Warning: instead of C-style syntax, use D-style syntax 'short[10] s'
.\dub\packages\arsd-master\arsd\simpledisplay.d(2244,14): Warning: instead of C-style syntax, use D-style syntax 'arch_ulong[5] l'
.\dub\packages\arsd-master\arsd\simpledisplay.d(2317,13): Warning: instead of C-style syntax, use D-style syntax 'arch_ulong[24] pad'
.\dub\packages\arsd-master\arsd\curl.d(69,8): Error: module md5 is in file 'std\md5.d' which cannot be read
```

``` d
import arsd.cgi;
void yourFunction(Cgi cgi) {
    cgi.write("Hello, world!");
}
mixin GenericMain!yourFunction;
```

**Comment by adamdruppe** [comment]
You seem to have a really old version of the code.

Are you using the master branch?

**Comment by nin-jin** [comment]
I was simply added this dependency:

```json
  "dependencies": {
    "arsd": "~master"
  }
```

**Comment by adamdruppe** [comment]
On Sat, Mar 12, 2016 at 05:20:38AM -0800, nin-jin wrote:
>     "arsd": "~master"

Oh, that's your mistake.

My package is called "arsd-official". "arsd" is an old
fork someone else did years ago and it is now abandoned.

**Comment by nin-jin** [comment]
```json
  "dependencies": {
    "arsd-official": "~master"
  }
```

```sh
Fetching arsd-official ~master (getting selected version)...
Placing arsd-official ~master to .\dub\packages\...
WARNING: A deprecated branch based version specification is used for the dependency arsd-official. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Invalid source/import path: C:\Users\jin\AppData\Roaming\dub\packages\arsd-official-master\dummy
Invalid source/import path: C:\Users\jin\AppData\Roaming\dub\packages\arsd-official-master\dummy
Configuration 'library' of package arsd-official:cgi contains no source files. Please add {"targetType": "none"} to it's package description to avoid building it.
Configuration 'library' of package arsd-official:http contains no source files. Please add {"targetType": "none"} to it's package description to avoid building it.
Configuration 'library' of package arsd-official:script contains no source files. Please add {"targetType": "none"} to it's package description to avoid building it.
Performing "debug" build using dmd for x86.
my-app ~master: building configuration "application"...
source\app.d(238,8): Error: module cgi is in file 'arsd\cgi.d' which cannot be read
```

**Comment by adamdruppe** [comment]
Ah, the dub.json capitalization was wrong. Fixed now, probably have to wait for the
code.dlang.org to scan it again though.

BTW, I really dislike dub and do not use it. A simpler alternative is to just download
the individual files you like and add them to your project's source. cgi.d is stand alone
in all except fastcgi modes, so it is easy to use without other dependencies.

**Comment by nin-jin** [comment]
I am creating a librarry. Not an application. :-)

**Comment by nin-jin** [comment]
Now:
```
> dub
source\app.d(238,8): Error: module cgi is in file 'arsd\cgi.d' which cannot be read
import path[0] = source
import path[1] = C:\D\dmd2\windows\bin\..\..\src\phobos
import path[2] = C:\D\dmd2\windows\bin\..\..\src\druntime\import
```

**Comment by rikmeijer** [comment]
I have the same problem, it compiles when using dmd with -I flag

**Comment by adamdruppe** [comment]
I'm sure dub is doing something weird here, but I don't actually use dub and don't know just what its problem is, I'll have to mess with it later. (The way I do it is just add the module to my dmd command. Always works without issue...)

**Comment by rikmeijer** [comment]
Can you show how that works?

Op ma 14 mrt. 2016 17:09 schreef Adam D. Ruppe <notifications@github.com>:

> I'm sure dub is doing something weird here, but I don't actually use dub
> and don't know just what its problem is, I'll have to mess with it later.
> (The way I do it is just add the module to my dmd command. Always works
> without issue...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamdruppe/arsd/issues/77#issuecomment-196387552>.
>
-- 

Met vriendelijke groet,
Rik Meijer

**Comment by nin-jin** [comment]
Works if i relocate your sources to "./source/arsd" from ".". "sourcePaths" and "importPaths" not works.
