### ISSUE TITLE
256 color support in terminal.d

### ISSUE THREAD

**Issue by zyedidia** [adamdruppe/arsd#78]
Does terminal.d support displaying 256 colors or even true color in terminals that support it?

Thanks for your help.

**Comment by adamdruppe** [comment]
On Sun, Mar 13, 2016 at 09:46:33AM -0700, Zachary Yedidia wrote:
> Does terminal.d support displaying 256 colors or even true color in terminals that support it?

Not exactly, you need to output the sequence yourself with 
terminal.writeStringRaw() right now.

It is at the top of my todo list though, I'll be adding a convenience
function for this in a couple weeks with some kind of feature fallback
too.

**Comment by adamdruppe** [comment]
I really hate unix terminals. There's no reliable way to detect features like this - everyone pretends to be xterm!

**Comment by adamdruppe** [comment]
And implemented:

https://github.com/adamdruppe/arsd/commit/a377f3ac8dc19eb8599cbd96aa3120800417ee70

```
void main() {
        auto terminal = Terminal(ConsoleOutputType.linear);
        terminal.setTrueColor(RGB(255, 0, 255), RGB(255, 255, 255));
        terminal.writeln("Hello, world!");
}
```

You can define them in RGB form and it will automatically use 256 color or 16 color depending on detected terminal. If you actually want a specific xterm color number, `xtermPaletteIndexToColor(idx)` will return an RGB for it.

**Comment by adamdruppe** [comment]
True color isn't fully implemented yet... I know the string but don't know how to get a reliable fallback detection yet, but the API is designed so it should just work when I do figure it out, and otherwise the 256 color fallback has wide support and should be good enough for most text stuff anyway.
