### ISSUE TITLE
dom.d Error: cannot call public/export function parentNode from invariant

### ISSUE THREAD

**Issue by bubnenkoff** [adamdruppe/arsd#84]
source\dom.d(2992,21): Error: cannot call public/export function parentNode from invariant
issue in latest DOM version

**Comment by adamdruppe** [comment]
On Tue, Apr 26, 2016 at 12:20:19AM -0700, Dmitry Bubnenkov wrote:
> source\dom.d(2992,21): Error: cannot call public/export function parentNode from invariant
> issue in latest DOM version

try it now

I had to do some changes recently to make DocumentFragment work like
it is supposed to according to standard and I probably broke a couple
things, so let me know if anything else broke for you.
