### ISSUE TITLE
htmlwidget.d?

### ISSUE THREAD

**Issue by Ajusa** [adamdruppe/arsd#86]
Where is the module? I can't seem to find it.
Also, I really love these libraries. They have helped me out a lot!

**Comment by adamdruppe** [comment]
On Fri, May 27, 2016 at 05:38:41AM -0700, Arham Jain wrote:
> Where is the module? I can't seem to find it.

Oh, I never git added it. Put up now, but I haven't even tried to
compile it for a long time, it probably doesn't work anymore.

> Also, I really love these libraries. They have helped me out a lot!

cool

**Comment by Ajusa** [comment]
It's fine if it doesn't work; I just need something to learn from. Thanks!

**Comment by adamdruppe** [comment]
On Sat, May 28, 2016 at 04:58:35AM -0700, Arham Jain wrote:
> It's fine if it doesn't work; I just need something to learn from. Thanks!

It is pretty incomplete too!

But it did manage to do some basic layout and css stuff - my website
looked OK with it (but not good). My code is an inefficient mess however.

**Comment by Ajusa** [comment]
Actually, I have a quick question about your modules: Do you know how to go from a javascript object to a JSON string? Does html.d provide anything like that? I can't serialize one string I am using because it was in the script tag.
`{hello:"world"}` - I have this
vs
`{"hello":"world"}` - I need to go to this.
Thanks!
