### ISSUE TITLE
not enough cursor reply answer

### ISSUE THREAD

**Issue by joelcnz** [adamdruppe/arsd#90]
Using OSX, (also, the cursor jumps up, some times, when start to type):

object.Exception@../arsdLib/source/arsd/terminal.d(2994): not enough cursor reply answer
----------------
4   jyble                               0x0000000103118313 void arsd.terminal.LineGetter.updateCursorPosition() + 487
5   jyble                               0x00000001031180ec void arsd.terminal.LineGetter.startGettingLine() + 160
6   jyble                               0x000000010311719a immutable(char)[] arsd.terminal.LineGetter.getline(arsd.terminal.RealTimeConsoleInput*) + 118
7   jyble                               0x00000001031124d9 immutable(char)[] arsd.terminal.Terminal.getline(immutable(char)[]) + 253
8   jyble                               0x0000000103080edb _Dmain + 347
9   jyble                               0x0000000103137953 D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv + 39
10  jyble                               0x0000000103137887 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 35
11  jyble                               0x00000001031378f8 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() + 44
12  jyble                               0x0000000103137887 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 35
13  jyble                               0x00000001031377ed _d_run_main + 497
14  jyble                               0x0000000103082301 main + 33
15  libdyld.dylib                       0x00007fff93f0c5ac start + 0
16  ???                                 0x0000000000000000 0x0 +

**Comment by adamdruppe** [comment]
On Tue, Jul 19, 2016 at 11:08:38PM -0700, Joel Christensen wrote:
> Using OSX, (also, you got the cursor jumps up when going to type):
> 
> object.Exception@../arsdLib/source/arsd/terminal.d(2994): not enough cursor reply answer

do you have the newest version? The line numbers don't line up.

I have seen this before and I *think* I fixed it but not sure. If not,
it is probably some buffer flushing.

**Comment by joelcnz** [comment]
I've installed the newest now. Thanks.
