### ISSUE TITLE
arsd.dom parsing XML/HTML wrong

### ISSUE THREAD

**Issue by WebFreak001** [adamdruppe/arsd#91]
```xml
<foo>
	<bar
		hello="world"
	/>
</foo>
```

gets parsed as

```xml
<foo>
	hello="world" />
</foo>
```

And in strict mode it crashes because of `wtf, zero length attribute name`

This is valid XML & HTTP though and it should result in

```xml
<foo>
	<bar hello="world"/>
</foo>
```

instead of crashing or ignoring `<bar>`

**Comment by adamdruppe** [comment]
On Thu, Jul 28, 2016 at 06:59:15AM -0700, Jan Jurzitza wrote:
> This is valid XML & HTTP though and it should result in

blargh, it worked for me.  Are you sure the ascii quotes were used in the original file? Maybe I copy/pasted wrong from github.

**Comment by WebFreak001** [comment]
With \r\n line endings

**Comment by adamdruppe** [comment]
On Thu, Jul 28, 2016 at 08:27:52AM -0700, Jan Jurzitza wrote:
> With \r\n line endings

ah, I see it now! thanks, should be an easy fix.

**Comment by adamdruppe** [comment]
BTW, this is so wrong, I can't believe I haven't noticed this before. Document.toString is supposed to always be well-formed xml. Not necessarily valid, but no stray characters. wow.

**Comment by adamdruppe** [comment]
OK, try it now.

**Comment by WebFreak001** [comment]
um I can test it tomorrow again when I'm at work

**Comment by adamdruppe** [comment]
On Thu, Jul 28, 2016 at 08:34:39AM -0700, Jan Jurzitza wrote:
> um I can test it tomorrow again when I'm at work

yup just let me know

thanks!

**Comment by WebFreak001** [comment]
Yep, works now thx
