### ISSUE TITLE
TrueColorImage.setPixel not working on the last 3 pixels (bottom-right part of the image)

### ISSUE THREAD

**Issue by glathoud** [adamdruppe/arsd#92]
First of all many thanks for arsd. Been using color.d and png.d intensively :)

Use case: created a `TrueColorImage` from scratch, size 256x256 pixels, and started to write colors in it, pixel per pixel, using `setPixel(x,y,color)`.

Everything fine, except for the last 3 (rightmost) pixels of the last line, also x = 253, 254, 255 and y= 255, which remain empty (transparent).

I found that line in the code source of color.d:
```
if (pos+3 < imageData.bytes.length/4) imageData.colors.ptr[pos] = clr;
```
shouldn't it be without the `+3`? Like this:
```
if (pos < imageData.bytes.length/4) imageData.colors.ptr[pos] = clr;
```
This fixes my problem.

**Comment by glathoud** [comment]
Created pull request https://github.com/adamdruppe/arsd/pull/93

**Comment by adamdruppe** [comment]
On Thu, Oct 13, 2016 at 01:27:48AM -0700, Guillaume Lathoud wrote:
> I found that line in the code source of color.d:

Oh yeah, we put in some checks for bounds and just idiot-brained that one.

Thanks for the fix!
