### ISSUE TITLE
Phobos no longer provides setmode() binding - this breaks cgi.d

### ISSUE THREAD

**Issue by KirillKryukov** [adamdruppe/arsd#95]
As of dmd 2.072.0, phobos no longer offers a binding for setmode(), which is used in cgi.d. The binding might be added to druntime in the future, but I've no idea if and when it will happen. In the meantime I suggest to add a binding into cgi.d (as suggested by Jonathan M Davis in the Learn group):

version(Windows)
{
    version(CRuntime_DigitalMars)
    {
        extern(C) int setmode(int, int) nothrow @nogc;
    }
    else version(CRuntime_Microsoft)
    {
        extern(C) int _setmode(int, int) nothrow @nogc;
        alias setmode = _setmode;
    }
    else static assert(0);
}

**Comment by adamdruppe** [comment]
On Fri, Nov 04, 2016 at 12:53:48AM -0700, KirillKryukov wrote:
> As of dmd 2.072.0, phobos no longer offers a binding for setmode()

cool, added.

**Comment by KirillKryukov** [comment]
Thanks!
