### ISSUE TITLE
Render opengl text

### ISSUE THREAD

**Issue by Stretto** [adamdruppe/arsd#96]
Nevermind, got it to work. Thanks! (can't seem to delete this "issue")?

**Comment by adamdruppe** [comment]
On Fri, Feb 03, 2017 at 09:43:02PM -0800, Stretto wrote:
> Is there any capabilities to render opengl strings in any of your modules?

Yes, you need to render it to an image first with something like
ttf.d, then draw the image as a texture in opengl.

See the gamehelpers.d module and do something like

```
auto font = TtfFont(std.file.read("font.ttf"));
auto text = new OpenGlTexture(&font, 12 /* size */, "some text");

// render it to the screen after you set up your opengl matrixes
text.draw(0, 0);
```


The function `arsd.gamehelpers.create2dWindow(title, width, height)`
returns a `SimpleWindow` (from simpledisplay.d) with a matrix set up
for 2d rendering with a one-to-one orthographic projection.


You can also draw 3d scenes, then change to a 2d matrix and draw text
on the screen if you are doing stuff like overlay HUD over a scene, drawing
with the same technique.

If you are drawing changing text, you may wish to cache the OpenGlTexture
created for various strings so they are reused.
