### ISSUE TITLE
simpledisplay.d 

### ISSUE THREAD

**Issue by EmTee70** [adamdruppe/arsd#98]
I needed to define 2 times:
enum CLOCK_MONOTONIC = 1;  // 1 was just guess.
Additionally in line 1309 and 4924

The compilation errors where:
src/simpledisplay.d(4947): Error: no property 'CLOCK_MONOTONIC' for type 'tfd', did you mean 'CLOCK_MONOTONIC'?
src/simpledisplay.d(4895): Error: function simpledisplay.SimpleWindow.NativeSimpleWindowImplementation!().eventLoop no return exp; or assert(0); at end of function
src/app.d(20): Error: template instance simpledisplay.SimpleWindow.eventLoop!(void delegate() @system, void delegate(KeyEvent event) @system, void delegate(MouseEvent event) @system, void delegate(dchar ch) @system) error instantiating
src/simpledisplay.d(1312): Error: no property 'CLOCK_MONOTONIC' for type 'tfd', did you mean 'CLOCK_MONOTONIC'?

**Comment by adamdruppe** [comment]
What OS are you on and what version of dmd do you have?

**Comment by EmTee70** [comment]
Oh, you are faster than light....
dmd --version
DMD32 D Compiler v2.072.2
Copyright (c) 1999-2016 by Digital Mars written by Walter Bright

32 Bit: /etc/os-release: 
NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.10"

**Comment by adamdruppe** [comment]
On Mon, Mar 20, 2017 at 12:12:44PM -0700, EmTee70 wrote:
> DMD32 D Compiler v2.072.2

huh, that should work fine, the definition of that constant is included
with the compiler now...

**Comment by EmTee70** [comment]
I tried to use it with/via DUB, and hat to change additionally two things.
a) Only import simpledisplay.d not arsd.simpledisplay.d
Seems to me a module definition file is missing in the dub package (arsd.d).
b) If I do not place an additional  targetType "executable" in dub.sdl
I get a lib build.

But now It worked with and without DUB and I am very thankful for your work offering easy access to graphic for newcomers in this area.

**Comment by EmTee70** [comment]
Hi Adam.
On Ubuntu 14.04. our office server
mt@spm8c:~/eisman2db$ dmd --version
DMD64 D Compiler v2.073.0
Copyright (c) 1999-2016 by Digital Mars written by Walter Bright

the same problem with 

> no property 'CLOCK_MONOTONIC' for type 'tfd', did you mean 'CLOCK_MONOTONIC'?

occurred.

**Comment by adamdruppe** [comment]
try the newest version of the file i just tried something else

**Comment by EmTee70** [comment]
Hi Adam. Now a new error..
coral ~master: building configuration "application"...
../../.dub/packages/arsd-official-1.1.0/arsd-official/simpledisplay.d(6291,5): Warning: statement is not reachable
../../.dub/packages/arsd-official-1.1.0/arsd-official/simpledisplay.d(6291,5): Warning: statement is not reachable
../../.dub/packages/arsd-official-1.1.0/arsd-official/simpledisplay.d(6291,5): Warning: statement is not reachable
dmd failed with exit code 1.

Regards mt.

**Comment by adamdruppe** [comment]
On Wed, Mar 22, 2017 at 08:20:47AM -0700, EmTee70 wrote:
> Hi Adam. Now a new error..

oh just  a warning

fixed

**Comment by EmTee70** [comment]
Thank you, I just removed the 'break;' myself, I am still so new I even don't know how to say to ignore a warning. Do you know when this new version will be available via dub, too? How often is it updated?

Is there a method in arsd to save a simpledisplay image as .png or .jpg?

**Comment by adamdruppe** [comment]
On Wed, Mar 22, 2017 at 09:27:04AM -0700, EmTee70 wrote:
> Thank you, I just removed the 'break;' myself, I am still so new I even don't know how to say to ignore a warning.

on dub it is a "allowWarnings" setting I think in the config.

> Do you know when this new version will be available via dub, too? How often is it updated?

If your version is ~master it should update basically immediately.

> Is there a method in arsd to save a simpledisplay image as .png or .jpg?

It can do png definitely. Grab the png.d file there too, add it to your src,
then

import arsd.png;

Image i =  .....;

writePng("file.png", i.toTrueColorImage());

and it should work

**Comment by EmTee70** [comment]
First thank you, for your advice!
But now I realized, my last question was misleading. 
Is there a way to get the window content from a simpledisplay window, to save it as an image (.png)? 

I look around but I found no solution for the ....; part in your suggestion.

**Comment by adamdruppe** [comment]
On Wed, Mar 22, 2017 at 12:52:32PM -0700, EmTee70 wrote:
> Is there a way to get the window content from a simpledisplay window, to save it as an image (.png)? 

Oh no, I haven't gotten around to implementing that function yet.

> I look around but I found no solution for the ....; part in your suggestion.

If you have an image you are drawing to the window, you can save the image, but there isn't a "get image from window" function yet. (It isn't too hard to add but I am doing other things right now...)

**Comment by adamdruppe** [comment]
I finally got around to actually implementing this function:
