### ISSUE TITLE
simpledisplay.d

### ISSUE THREAD

**Issue by EmTee70** [adamdruppe/arsd#99]
A more general question.
To get the examples compiled I needed to install several missing libs.
   sudo apt-get install libglc-dev
and
   sudo apt-get install libx11-dev

solved the issue, but it would be useful for gui programing starters like me, to place this info somewhere. (?)
Second question: Would it be possible with dub to specify such dependencies, so they are installed automatically?
I know dub is not yours ... :-)

**Comment by adamdruppe** [comment]
On Mon, Mar 20, 2017 at 12:08:29PM -0700, EmTee70 wrote:
> To get the examples compiled I needed to install several missing libs.
>    sudo apt-get install libglc-dev
> and
>    sudo apt-get install libx11-dev

Oh, on ubuntu? I can add a note about that to the documentation
but since it is an OS thing, it needs to be done separately.

**Comment by adamdruppe** [comment]
I added a note to the docs:

http://dpldocs.info/experimental-docs/arsd.simpledisplay.html#installation-instructions
